README.md
source/layouts/layout.erb
source/stylesheets/screen.css.scss

Includes layout fixes for local development along with styling tweaks to address code sample and code annotation alignment. Also includes updates to the docs README.

Doc updates

---

CONTRIBUTING.md

Fixed subscribe/unsubscribe links.

Corrected subscribe/unsubscribe procedures for email lists.

---

examples/FedRAMP/README.md
examples/FedRAMP/readme.md

Made some minor edits to PR #187 from @brianrufgsa.

Merge Brianrufgsa feature fed ramp readme

---

source/includes/schema/_catalogXML.md
source/includes/schema/_profileXML.md

[WIP] Created draft catalog XML examples in support of issue #139 
Created an initial draft of catalog XML examples embedded within the _catalogXML.md schema documentation file.
* [N/A] Have you written new tests for your core changes, as applicable?
* [N/A] Have you included examples of how to use your new feature(s)?

[WIP] Catalog XML examples for issue #139

---

source/roadmap.html.md

Completed initial draft roadmap addressing #183.

Feature roadmap

---

content/nist.gov/SP800-53/rev4/NIST_SP-800-53_rev4_catalog.xml
content/nist.gov/SP800-53/rev4/NIST_SP-800-53_rev4_declarations.xml

These changes reflect updates in view of policy plus also issues #175 #218 #221
* Labels (`prop[@class='label']` have been rewritten to reflect only their "short form" i.e. explicit label as given in the PDF source, not the (implicit) "expanded" label sometimes attributed to items by cross-references elsewhere. This entails "trimming" labels so that "AC-3(a)(1)" becomes "(1)".
* Labels inside `objective` parts, however, are exempted from this rule; where given in long form (in the source data) they remain long-form. (The PDF of Appendix A has them in long form so we still follow the rule of presentational fidelity.)
* Again, however, an exception: any label is *removed* that (merely) echoes the label on its parent, i.e. a label "AC-2" is removed from a part when that is already the label …

Restoring item labels to 'page fidelity' (PDF source) in SP800-53 catalog

---

.circleci/config.yml

Quick fix to the CircleCI build configuration.

fixed build config issue preventing git checkout

---

.circleci/config.yml

Fixing circleci config build issue.

Build fix missing checkout

---

.circleci/config.yml
build/ci-cd/copy-and-convert-content.sh
build/ci-cd/generate-content-converters.sh
build/ci-cd/generate-schema-documentation.sh
build/ci-cd/generate-schema.sh
build/ci-cd/validate-content.sh

Added persistence of built artifacts to allow repo to be updated at the end of the build.

Fix workspace

---

.circleci/config.yml
build/ci-cd/config/metaschema-docs

A small fix to the deployment commands.

fixed deployment commands

---

.circleci/config.yml

Fixed bug causing docs to not be published to site.

Fix document generation and publication

---

.circleci/config.yml

Fixed missing saxon dependency.

fixed missing maven dependency

---

content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_catalog.xml
src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_catalog.xml
src/metaschema/oscal-resources-metaschema.xml
xml/schema/oscal-catalog-schema.xsd
xml/schema/oscal-profile-schema.xsd

Addresses #235 and #346. Minor changes to schema files and SP800-53 data.

Issue235 required hrefs

---

.circleci/config.yml
.gitignore
build/ci-cd/README.md
build/ci-cd/schematron-init.sh
build/ci-cd/svrl-to-plaintext.xsl
build/ci-cd/validate-metaschema.sh
build/metaschema/lib/metaschema-check.sch

Added support for Schematron validation of metaschema files.

Validate metaschema using schematron

---

src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_catalog.xml

Completing Issue #235 after noting problems in #381.
The corrections here:
* 'Chapter 3' link now points to PDF version
* Internal links corrected

Found and corrected more broken links in SP800-53rev4 catalog

---

.circleci/config.yml
build/ci-cd/validate-metaschema.sh

Fixed a logic error causing failed metaschema schematron validations to appear as successful validations. Also, added support for storing SVRL results as CircleCI artifacts.

Fix ci deploy

---

.circleci/config.yml

Testing detection of changed files

Testing detection of changed files

---

.circleci/config.yml
build/ci-cd/common-environment.sh
build/ci-cd/copy-and-convert-content.sh
build/ci-cd/generate-content-converters.sh
build/ci-cd/generate-schema-documentation.sh
build/ci-cd/generate-schema.sh
build/ci-cd/saxon-init.sh
build/ci-cd/schematron-init.sh
build/ci-cd/validate-content.sh
build/ci-cd/validate-metaschema.sh

Adding colorization for messages in build scripts. Also added a build optimization to not publish generated content if no changes were made.

Added colorization to messages in scripts

---

.circleci/config.yml

Properly capture exit code in script.

Fixed exit code problem that causes the build to fail

---

build/metaschema/lib/metaschema-check.sch
build/metaschema/lib/metaschema.xsd
src/content/fedramp.gov/xml/FedRAMP_HIGH-baseline_profile.xml
src/content/fedramp.gov/xml/FedRAMP_LOW-baseline_profile.xml
src/content/fedramp.gov/xml/FedRAMP_MODERATE-baseline_profile.xml
src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_HIGH-baseline_profile.xml
src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_LOW-baseline_profile.xml
src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_MODERATE-baseline_profile.xml
src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_catalog.xml
src/metaschema/oscal_catalog_metaschema.xml
src/metaschema/oscal_metadata_metaschema.xml

Addresses requirements described in #57 for representing the version of an OSCAL model to which a document conforms.

Issue57 schema version support

---

.gitignore

Ignoring VSCode files

---

.circleci/config.yml
.gitignore
build/ci-cd/config/release-content
build/ci-cd/package-release.sh

Adding scripting to attach releases bundles to a new release. Related to issue #341.

Add release automation support

---

.circleci/config.yml
build/ci-cd/copy-and-convert-content.sh

Replaces jsome with jq to address a newline bug.

Broken json fix

---

docs/README.md

Updates the website development documentation with instructions on building and serving locally using Docker.

Include Docker instructions for local website development

---

build/ci-cd/package-release.sh
src/content/fedramp.gov/xml/FedRAMP_HIGH-baseline_profile.xml
src/content/fedramp.gov/xml/FedRAMP_LOW-baseline_profile.xml
src/content/fedramp.gov/xml/FedRAMP_MODERATE-baseline_profile.xml
src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_HIGH-baseline_profile.xml
src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_LOW-baseline_profile.xml
src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_MODERATE-baseline_profile.xml
src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_catalog.xml
src/metaschema/oscal_catalog_metaschema.xml
src/metaschema/oscal_metadata_metaschema.xml
src/metaschema/oscal_profile_metaschema.xml
src/metaschema/oscal_ssp_metaschema.xml

Repairing the release script and fixing the schema versions.

Fixed release script. Renamed version in files.

---

src/content/fedramp.gov/xml/FedRAMP_HIGH-baseline_profile.xml
src/content/fedramp.gov/xml/FedRAMP_LOW-baseline_profile.xml
src/content/fedramp.gov/xml/FedRAMP_MODERATE-baseline_profile.xml
src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_HIGH-baseline_profile.xml
src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_LOW-baseline_profile.xml
src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_MODERATE-baseline_profile.xml
src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_catalog.xml
src/release/release-notes.txt

Changed OSCAL version to semver format.

Changed OSCAL version to semver format

---

src/content/ssp-draft/readme.md

Trivial typo fix to docs

---

src/content/ssp-draft/OSCAL Implementation Layer - FedRAMP System Security Plan (SSP) Modeling.md

Trivial typo fix for SSP modelling doc.

---

src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_HIGH-baseline_profile.xml

This makes it consistent with other profiles, so it is easier to diff(1)
the files and see actual differences in requirements.
Partly complies: Followed https://github.com/usnistgov/OSCAL/blob/master/CONTRIBUTING.md#contributing-to-the-oscal-repository but the rest is too vague to claim compliance.

Add description to SP-800-53 HIGH baseline profile backmatter.

---

.circleci/config.yml

fixed maven version

---

CONTRIBUTING.md
README.md

The main README should be concise and merely point users to the website, official NIST project page, and `CONTRIBUTING.md` doc for more info.
CC @david-waltermire-nist for review

Update readme and move repo structure to contributing doc

---

docs/content/documentation/schemas/oscal-prose.md

Documenting the Markdown <-> HTML mapping (#357).

Document HTML <-> Markdown mapping

---

.circleci/config.yml

Fixing broken maven dependency in build.

Fixing maven version to allow correct download

---

.circleci/config.yml

One more quick fix to ensure generated documentation is properly unpacked.

Master build fix

---

.circleci/config.yml

Hugo conversion

---

.circleci/config.yml
.gitmodules
README.md
docs/Gemfile.lock

adding gemfile

---

.gitmodules
docs/config.yaml
docs/content/contribute/_index.md

Addressing encoding issues and a few minor bug fixes.

Fixing site bugs

---

docs/content/contribute/_index.md
docs/content/contribute/contact.md
docs/content/contribute/roadmap.md
docs/content/downloads/other-resources.md

Also more text around contributing.

Added note about gitter

---

docs/assets/scss/hugo-uswds-custom.scss

Added print styles to the website CSS.

Integration of print styles

---

docs/content/_index.md
docs/content/contribute/_index.md
docs/content/contribute/contact.md
docs/content/contribute/devlunch.md
docs/content/documentation/schema/_index.md
docs/content/documentation/schema/catalog/_index.md
docs/content/documentation/schema/component/_index.md
docs/content/documentation/schema/profile/_index.md

Minor updates to URLS and website contents.

Minor website updates for workshop

---

docs/content/downloads/other-resources.md

Posting workshop slides to the resources page.

Workshop update

---

src/content/mini-testing/Unit-Testing-Description.md
src/content/ssp-example/example-component.json
src/content/ssp-example/ssp-example.json

Minor typo fixes in src/content examples.

---

src/metaschema/oscal_ssp_metaschema.xml

Typo fix in SSP metaschema

---

build/metaschema/lib/metaschema-jsondocs-hugo-uswds.xsl
build/metaschema/lib/metaschema-jsonobject-map.xsl

Addresses small but bothersome glitches in schema docs.
@david-waltermire-nist let's discuss this before merging (we might not be quite done yet).

Nov2019 docs fix

---

docs/content/contribute/devlunch.md
src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_catalog.xml
src/metaschema/oscal_metadata_metaschema.xml

Updating dev lunch info.
Fixed stray whitespace in 800-53 catalog.
Updating to latest USWDS theme.
Fixed namespace bug in metadata metaschema.

Misc site updates

---

docs/content/contribute/devlunch.md

Site maintenance

---

docs/content/learnmore/architecture/_index.md

Typo fixes in docs

---

build/Dockerfile
build/README.md
build/ci-cd/config/content
build/ci-cd/copy-and-convert-content.sh
build/ci-cd/run-all.sh
build/docker-compose.yml

This PR contains a Docker container configuration and setup instructions for establishing the necessary build environment to run the scripts used by the CI/CD pipeline.

Adding docker configuration and README for build setup

---

build/ci-cd/config/release-content

Adding correct files to release

Adding correct files to release

---

json/README.md
src/release/content-upgrade/add-uuids.xsl
src/release/content-upgrade/oscal-m2-m3-elements.xsl
src/release/content-upgrade/rewrite-links.xsl
src/specifications/profile-resolution/readme.md
src/utils/util/resolver-pipeline/readme.md
xml/README.md

This PR includes improvements to the content upgrade pipeline for Milestone 2 conversion to Milestone 3 OSCAL, as described in #694.

Improving content upgrade XSLTs for better handling of SSPs

---

docs/content/contribute/dev-lunch/_index.md
docs/content/contribute/model-review/_index.md

Fixing dates on meeting pages.
Updating metaschema commit to fix #701.

Fix issue 701 and missing meeting times

---

build/README.md

The edits in the single changed file should be self-explanatory in the context of #737.

Edits to remove broken links #737

---

docs/content/contribute/_index.md

Fix small typo in documentation

---

src/utils/util/convert/readme.md

This readme had not been edited since resources were reorganized.
Updates a readme to reduce confusion.

Added clarification/update

---

build/README.md
build/ci-cd/run-all.sh

Simplifying and updating build environment setup.

Cleanup of Build Setup Documentation

---

src/metaschema/oscal_assessment-common_metaschema.xml

Changed relevant-evidence group name

---

docs/content/documentation/schema/assessment-layer/assessment-plan/json-model-map.md
docs/content/documentation/schema/assessment-layer/assessment-plan/json-schema.md
docs/content/documentation/schema/assessment-layer/assessment-plan/xml-model-map.md
docs/content/documentation/schema/assessment-layer/assessment-plan/xml-schema.md
docs/content/documentation/schema/assessment-results-layer/assessment-results/json-model-map.md
docs/content/documentation/schema/assessment-results-layer/assessment-results/json-schema.md
docs/content/documentation/schema/assessment-results-layer/assessment-results/xml-model-map.md
docs/content/documentation/schema/assessment-results-layer/assessment-results/xml-schema.md
docs/content/documentation/schema/assessment-results-layer/poam/json-model-map.md
docs/content/documentation/schema/assessment-results-layer/poam/json-schema.md
docs/content/documentation/schema/assessment-results-layer/poam/xml-model-map.md
docs/content/documentation/schema/assessment-results-layer/poam/xml-schema.md
docs/content/documentation/schema/catalog-layer/catalog/json-model-map.md
docs/content/documentation/schema/catalog-layer/catalog/json-schema.md
docs/content/documentation/schema/catalog-layer/catalog/xml-model-map.md
docs/content/documentation/schema/catalog-layer/catalog/xml-schema.md
docs/content/documentation/schema/implementation-layer/component/json-model-map.md
docs/content/documentation/schema/implementation-layer/component/json-schema.md
docs/content/documentation/schema/implementation-layer/component/xml-model-map.md
docs/content/documentation/schema/implementation-layer/component/xml-schema.md
docs/content/documentation/schema/implementation-layer/ssp/json-model-map.md
docs/content/documentation/schema/implementation-layer/ssp/json-schema.md
docs/content/documentation/schema/implementation-layer/ssp/xml-model-map.md
docs/content/documentation/schema/implementation-layer/ssp/xml-schema.md
docs/content/documentation/schema/profile-layer/profile/json-model-map.md
docs/content/documentation/schema/profile-layer/profile/json-schema.md
docs/content/documentation/schema/profile-layer/profile/xml-model-map.md
docs/content/documentation/schema/profile-layer/profile/xml-schema.md

Fixed broken legacy links.
Normalized terminology in format docs metadata.

Format documentation navigation cleanup

---

docs/content/contact/_index.md

Updating the contact information for subscribing and unsubscribing from the OSCAL mailing lists.
Resolves #781.

OSCAL mailing list contact updates

---

build/Dockerfile
build/README.md
build/docker-compose.yml

added ajv-cli to build installation documentation.
Updated docker container to use ajv-cli.

Documenting and integrating use of AJV for JSON validation

---

src/specifications/profile-resolution/profile-resolution-examples/catalogs/abc-full_catalog.xml
src/specifications/profile-resolution/profile-resolution-specml.xml
src/specifications/profile-resolution/specml-html-xslt1.xsl
src/utils/util/resolver-pipeline/oscal-profile-RESOLVE.xsl
src/utils/util/resolver-pipeline/oscal-profile-resolve-finish.xsl
src/utils/util/resolver-pipeline/oscal-profile-resolve-merge.xsl
src/utils/util/resolver-pipeline/oscal-profile-resolve-metadata.xsl
src/utils/util/resolver-pipeline/oscal-profile-resolve-modify.xsl
src/utils/util/resolver-pipeline/oscal-profile-resolve-select.xsl
src/utils/util/resolver-pipeline/testing/1_selected/select.xspec
src/utils/util/resolver-pipeline/testing/2_metadata/metadata.xspec
src/utils/util/resolver-pipeline/testing/3_merged/merge-as-is.xspec
src/utils/util/resolver-pipeline/testing/3_merged/merge-back-matter.xspec
src/utils/util/resolver-pipeline/testing/3_merged/merge-custom.xspec
src/utils/util/resolver-pipeline/testing/3_merged/merge.xspec
src/utils/util/resolver-pipeline/testing/4_modified/modify.xspec
src/utils/util/resolver-pipeline/testing/5_finished/finish.xspec

PR represents improvements to OSCAL Profile resolution (processing), addressing Issue #771.

Profile Resolution: updated unit tests, with repair to bug #771

---

src/metaschema/oscal_assessment-common_metaschema.xml
src/metaschema/oscal_assessment-plan_metaschema.xml
src/metaschema/oscal_assessment-results_metaschema.xml
src/metaschema/oscal_metadata_metaschema.xml
src/metaschema/oscal_poam_metaschema.xml
src/metaschema/oscal_ssp_metaschema.xml

Addressed group naming inconsistencies resolving #780.

Addressed group naming resolving #780

---

docs/assets/scss/schema-docs.scss

Further improved and enhanced documentation production, both schema docs pages and model maps. Addresses both #725 and #750.

M4 docs integration cont'd

---

docs/assets/scss/schema-docs.scss

SCSS changes to go along with usnistgov/metaschema#96

SCSS to go with usnistgov/metaschema#96

---

docs/assets/scss/schema-docs.scss
docs/content/documentation/schema/assessment-layer/assessment-plan/xml-schema.md
docs/content/documentation/schema/assessment-results-layer/assessment-results/xml-schema.md
docs/content/documentation/schema/assessment-results-layer/poam/xml-schema.md
docs/content/documentation/schema/catalog-layer/catalog/xml-schema.md
docs/content/documentation/schema/implementation-layer/component/xml-schema.md
docs/content/documentation/schema/implementation-layer/ssp/xml-schema.md
docs/content/documentation/schema/profile-layer/profile/xml-schema.md

This PR includes some SCSS changes and some mods to home markdown pages for schemas (removing contents now generated in the pipeline).

Updates to docs generation

---

docs/assets/scss/schema-docs.scss

Asymptotically approaching perfection. Still a little ways off.

Schema documentation enhancements

---

src/release/content-upgrade/oscal-m3-rc1-elements.xsl
src/release/content-upgrade/uuid/random-util.xsl
src/release/content-upgrade/uuid/reassign-uuids.xsl
src/release/content-upgrade/uuid/refresh-uuids.xsl

First cut at OSCAL M3-RC1 XML content converter, covering the change log through the SSP and component models (i.e., implementation layer).

OSCAL M3-RC1 XML content converter

---

src/metaschema/oscal_assessment-common_metaschema.xml
src/metaschema/oscal_assessment-plan_metaschema.xml

Final m4 push

---

src/metaschema/oscal_assessment-common_metaschema.xml
src/metaschema/oscal_implementation-common_metaschema.xml
src/metaschema/oscal_metadata_metaschema.xml
src/metaschema/shared-constraints/allowed-values-component_component_link-rel.ent
src/metaschema/shared-constraints/allowed-values-property-name-asset-type-values.ent

Final push 2

---

src/release/content-upgrade/catalog-link-tweak.xsl
src/release/content-upgrade/oscal-m3-rc1-elements.xsl

RC1 upgrade transformation now refreshes the time stamp. Also with another useful utility.

Fine adjustments to upgrade tranformations

---

src/metaschema/oscal_assessment-common_metaschema.xml
src/metaschema/oscal_assessment-results_metaschema.xml
src/metaschema/oscal_poam_metaschema.xml

Moved collected and expires from /*/result/finding to /*/result/observation
This PR is a rebase of PR #817. Resolves #813.

Daw ar move collected

---

src/metaschema/oscal_control-common_metaschema.xml
src/metaschema/oscal_implementation-common_metaschema.xml

Adding remarks to param and set-param.

adding optional remarks to param and set-param

---

src/metaschema/oscal_assessment-common_metaschema.xml
src/metaschema/oscal_assessment-plan_metaschema.xml
src/metaschema/oscal_assessment-results_metaschema.xml
src/metaschema/oscal_poam_metaschema.xml

This PR contains a few model changes to address feedback on the OSCAL 1.0.0 RC1 models.

Model Refactoring for RC2

---

src/metaschema/oscal_assessment-common_metaschema.xml
src/metaschema/oscal_assessment-plan_metaschema.xml
src/metaschema/oscal_assessment-results_metaschema.xml
src/metaschema/oscal_catalog_metaschema.xml
src/metaschema/oscal_component_metaschema.xml
src/metaschema/oscal_implementation-common_metaschema.xml
src/metaschema/oscal_poam_metaschema.xml
src/metaschema/oscal_profile_metaschema.xml

Multiple metaschema pipeline udates

---

docs/content/documentation/schema/assessment-layer/_index.md
docs/content/documentation/schema/assessment-results-layer/_index.md
docs/content/documentation/schema/implementation-layer/component/_index.md
docs/content/documentation/schema/implementation-layer/ssp/_index.md

Updated the four markdown documents that were still referencing the legacy architecture page to now link to the Layers and Models Reference page.

Updated broken doc links to fix #866

---

docs/assets/scss/schema-docs.scss
docs/content/documentation/schema/assessment-layer/assessment-plan/xml-schema.md

Addresses a set of issues with accuracy and legibility of documentation generated from metaschema sources, including model maps and model documentation.
#870 #849 #848 #847
Also usnistgov/metaschema#120 and several issues linked to it.

Enhancements and improvements to (generated) OSCAL model documentation

---

src/specifications/profile-resolution/profile-resolution-specml.xml
src/utils/util/resolver-pipeline/oscal-profile-resolve-functions.xsl
src/utils/util/resolver-pipeline/oscal-profile-resolve-merge.xsl
src/utils/util/resolver-pipeline/oscal-profile-resolve-metadata.xsl
src/utils/util/resolver-pipeline/oscal-profile-resolve-select.xsl
src/utils/util/resolver-pipeline/testing/2_metadata/metadata.xspec
src/utils/util/resolver-pipeline/testing/3_merged/merge-custom.xspec

Incremental improvements to Profile Resolution Spec along with changes to profile resolution demo to improve functionality and alignment.

Profile resolution specs and implementation improvements

---

src/metaschema/oscal_assessment-common_metaschema.xml
src/metaschema/oscal_assessment-plan_metaschema.xml
src/metaschema/oscal_assessment-results_metaschema.xml
src/metaschema/oscal_catalog_metaschema.xml
src/metaschema/oscal_complete_metaschema.xml
src/metaschema/oscal_component_metaschema.xml
src/metaschema/oscal_control-common_metaschema.xml
src/metaschema/oscal_implementation-common_metaschema.xml
src/metaschema/oscal_metadata_metaschema.xml
src/metaschema/oscal_poam_metaschema.xml
src/metaschema/oscal_profile_metaschema.xml
src/metaschema/oscal_ssp_metaschema.xml

Updates to OSCAL metaschemas reflecting improvements to datatype definitions.

Metaschema updates for v1.0.0

---

docs/content/concepts/layer/implementation/component-definition/_index.md

Fixing Typo for #946

---

src/metaschema/oscal_assessment-common_metaschema.xml
src/metaschema/oscal_component_metaschema.xml

Removing old cruft from the OSCAL Metaschemas.

Cleanup of comments in Metaschemas

---

docs/content/about/_index.md
docs/content/about/use-cases/_index.md
docs/content/concepts/layer/_index.md
docs/content/concepts/layer/control/catalog/_index.md
docs/content/concepts/layer/overview.md
docs/content/concepts/relations-to-other.md
docs/content/concepts/terminology/_index.md
docs/content/contribute/model-review/_index.md
docs/content/contribute/model-review/oscal-model-review.ics
docs/content/learn/presentations/_index.md
docs/content/learn/tutorials/_index.md
docs/content/learn/tutorials/catalog/_index.md
docs/content/learn/tutorials/validation-modeling.md
docs/content/reference/1.0.0-rc2/assessment-plan/json-definitions.md
docs/content/reference/1.0.0-rc2/assessment-plan/json-reference.md
docs/content/reference/1.0.0-rc2/assessment-plan/xml-definitions.md
docs/content/reference/1.0.0-rc2/assessment-plan/xml-reference.md
docs/content/reference/1.0.0-rc2/assessment-results/json-definitions.md
docs/content/reference/1.0.0-rc2/assessment-results/xml-definitions.md
docs/content/reference/1.0.0-rc2/plan-of-action-and-milestones/json-definitions.md
docs/content/reference/1.0.0-rc2/plan-of-action-and-milestones/json-reference.md
docs/content/reference/1.0.0-rc2/plan-of-action-and-milestones/xml-definitions.md
docs/content/reference/datatypes.md
docs/content/reference/release-notes.md
src/specifications/profile-resolution/profile-resolution-specml.xml

Website edits to resolve #947.

Addressing typos for issue #947.

---

build/Dockerfile

Fix entrypoint issue. Closes #983.

Fix Dockerfile entrypoint for best practice.

---

.gitmodules

Update metaschema branch config in submodule.

---

docs/content/learn/tutorials/validation-modeling.md

Fix prop syntax in validation component tutorial.

---

src/utils/util/oscal-content-validator.py

Resolves #1025
- [N/A] Have you added an explanation of what your changes do and why you'd like us to include them?
- [N/A] Have you written new tests for your core changes, as applicable?
- [N/A] Have you included examples of how to use your new feature(s)?
- [N/A] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

utils: fix SyntaxWarning on content validator

---

src/metaschema/oscal_assessment-common_metaschema.xml
src/metaschema/oscal_catalog_metaschema.xml
src/metaschema/oscal_control-common_metaschema.xml
src/metaschema/oscal_metadata_metaschema.xml
src/metaschema/oscal_profile_metaschema.xml
src/utils/util/readme.md

Adjustments to metaschema constraints to:
- fix a duplicate, malformed constraint
- remove use of "require"

Release 1.0 metaschema adjustments

---

src/utils/util/oscal-content-validator.py

Found import json was done twice. This removes the duplicate.

Removes duplicate import

---

src/metaschema/oscal_assessment-results_metaschema.xml
src/metaschema/oscal_catalog_metaschema.xml
src/metaschema/oscal_complete_metaschema.xml
src/metaschema/oscal_component_metaschema.xml
src/metaschema/oscal_control-common_metaschema.xml
src/metaschema/oscal_implementation-common_metaschema.xml
src/metaschema/oscal_metadata_metaschema.xml
src/metaschema/oscal_poam_metaschema.xml
src/metaschema/oscal_profile_metaschema.xml

This PR implements some useful touch-ups that is part, but potentially not all of usnistgov/OSCAL#1107.

Update Path for Schematron Validation of Metaschema Models

---

.github/workflows/metaschema-artifacts.yml
.github/workflows/package-release.yml
.github/workflows/website-artifacts.yml
build/README.md
build/ci-cd/README.md
build/ci-cd/python/readme.md
build/ci-cd/setup-ubuntu.sh
build/docker-compose.yml
docs/README.md
json/README.md
xml/README.md

This PR updates use of Saxon to version 10.6 per #1035.

Upgrade Saxon use to 10.6

---

git-cheat-sheet.md

Updating git-cheat-sheet.md file to replace the references to 'master' branch with 'main'

PR for issue 1198

---

.github/workflows/workflow-validate-repo-markdown.yml
build/config/.markdown-link-check/config.json
build/package-lock.json
build/package.json
src/metaschema/oscal_metadata_metaschema.xml

The regex for `metadata/location/address/country` is not properly formed. Corrected syntax errors. Resolves #1220.

Corrected metadata/location/address/country regex

---

src/metaschema/oscal_assessment-common_metaschema.xml

Fixes #1193 (for `oscal_assessment-common_metaschema.xml` only).
This PR doesn't change any functionality or logic.

Grammar fixes to `assessment-common` metaschema

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
LICENSE.md

Updates to contributing and licensing documentation to further clarify contributions are made under the [CC0 1.0 Universal public domain dedication](https://creativecommons.org/publicdomain/zero/1.0/). Updated NIST disclaimer boilerplate.

updated contributing and licensing information

---

build/README.md

This change updates and corrects documentation for developers to understand proper setup of local build environment. Closes usnistgov/OSCAL#1283.
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in …

Update Documentation for Developer Enviroment Setup

---

docs/content/about/news.md

Closes usnistgov/OSCAL#1316 detected through automated scheduled link checking.
- ~Have you written new tests …

Fix blog post from docker.com->mirantis.com

---

.github/ISSUE_TEMPLATE/feature_request.yaml

Moved comment in the acceptance criteria to the text box description.

Minor tweek to User Story template

---

docs/content/concepts/layer/control/catalog/sp800-53rev5-example.md

"Revision 5" for consistency with page copy and style.
... because we corrected this everywhere but in the title.

Corrected SP800-53 Example page title

---

src/specifications/profile-resolution/profile-resolution-specml.xml

Addresses #1312
Clarifies language in the Profile Resolution Specification regarding expectations regarding the validation of inputs as suggested on #1312.

Profile Resolution Spec clarification: validating imports

---

.github/workflows/workflow-generate-website-reference.yml
.github/workflows/workflow-generate-website.yml

Closes #1387.
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your …

Cache compiled hugo binary in the CI/CD pipelines.

---

src/metaschema/oscal_catalog_metaschema.xml

The OSCAL [SP 800-53 rev4 catalog](https://github.com/usnistgov/oscal-content/blob/main/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_catalog.xml) uses the following syntax:
```
<prop name="status" value="Withdrawn"/>
```
Which includes a capital case `Withdrawn`. This capitalization was normalized in the rev5 catalog as `withdrawn`.
This PR adds a deprecated value for `Withdrawn` to deal with backwards compatibility.

Added legacy Withdrawn status with deprecation entry

---

docs/config.yaml
docs/layouts/_internal/google_analytics_async.html
docs/layouts/html.html

Fix Hugo analytics config for usnistgov/OSCAL#1413.

---

src/metaschema/oscal_metadata_metaschema.xml

Add grouping construct to props for usnistgov/OSCAL#1064.

---

src/metaschema/oscal_profile_metaschema.xml
src/specifications/profile-resolution/profile-resolution-specml.xml

Updates to the Profile Resolution Specification and the Metaschema to better support the planned Mapping feature.
Addresses #538 #843 #1115

Profile Identifier Mapping

---

docs/content/learn/tutorials/_index.md
docs/content/learn/tutorials/profile/_index.md

This PR contains the first draft of the Profile Authoring tutorial, and required changes to the website Indexes to support it.

Profile tutorial

---

src/metaschema/oscal_profile_metaschema.xml

Suffix and Prefix support for reassigned identifiers.

DRAFT: Issue 1327 support prefix suffix during mapping

---

notes/oscal_rules.md

This document is draft notes that will later be adapted into one or more pages in the [pages.nist.gov/OSCAL]() to ready ongoing work from NIST and community contributors on educational framing content for usnistgov/OSCAL#1058.

[WIP] Explanatory Documentation and Notes for OSCAL Rules and Test Enhancements

---

docs/content/about/news.md

Closes usnistgov/OSCAL#1454.
Fixes upstream issue to revert workarounds in https://github.com/usnistgov/oscal-content/pull/139 and unblock https://github.com/ginger-anderson/CISControls_OSCAL/pull/1.
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes …

Update metaschema submodule for usnistgov/OSCAL#1454.

---

.github/workflows/workflow-validate-website-content.yml

Co-authored-by: AJ Stein <alexander.stein@nist.gov>
Closes #1506 
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website …

Added `--exclude-mail` arg to linkchecker workflow

---

.github/CODEOWNERS

Remove staff that were previously off-boarded and have inactive GitHub accounts.

Update CODEOWNERS for Current NIST OSCAL Staff

---

docs/content/contribute/model-review/meeting-2021-01-22.md

This resolves a formatting issue that was causing https://pages.nist.gov/OSCAL/contribute/model-review/ to render incorrectly
- ~Have you written new tests for your core changes, as applicable?
- ~Have you included examples of how to use your new feature(s)?

add some missing dashes

---

docs/content/contribute/define-meeting/_index.md

Woops, clarify DEFINE schedule for #1560 more.
@Compton-NIST had pointed this I think more than once, and in the rebase and cleanup for final review and merge I missed this bit. Hat tip to @DavidAllardyce for bringing it back to my attention.
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and …

Clarify DEFINE schedule for #1560 more

---

docs/content/contribute/_index.md
docs/content/contribute/model-engineering-meeting/meeting-2023-01-26.md

Update missed page with public meeting index missed in usnistgov/OSCAL#1560.

Update missed page with public meeting index.

---

docs/content/learn/presentations/mini-workshop/_index.md

Updated the 2022 (end of year) presentations by linking the slides and the videos. Added the 2023 scheduled events

Updates to OSCAL mini workshops page

---

docs/content/tools/_index.md

Fixing header in the Tools page of OSCAL repository by removing extra code in the header.

Fixing Header in the Tools Page of OSCAL Repository

---

decisions/0001-record-architecture-decisions.md
decisions/0002-communicating-nist-oscal-events-to-the-public.md
docs/content/contact/_index.md
docs/content/contribute/_index.md
docs/content/events/_index.md

This is follow on work missed in #1638 and #1642. Re-opening #1408 to make AC and spirit of issue are met before closing.
Observe the new header events, it was not added in merging the previous code. Below is a picture of the changed site running locally.

Fix Missing Header for Events Page and Mark ADRs Actually Approved

---

docs/content/examples/_index.md

We created a page similar to [OSCAL tools] (https://pages.nist.gov/OSCAL/tools/) that provides links to OSCAL content (catalogs, profiles, component-definitions, etc.) generated by NIST and website where community can contribute. 

Added New Examples Page, Issue: #1294

---

decisions/0003-github-labels-decluttering.md

Adding an ADR that identifies the Git Hub labels we need and/or want to use and the ones we want to remove. The labels are also grouped per categories in this ADR.
For additional actions related to issue #1496 , a.k.a [Draft ADR How to Handle EPICs and Related Issues](https://hackmd.io/eUhzIQx3RW6zYcGZ_iIJUQ), additional internal meetings are necessary.
Minutes of the https://github.com/usnistgov/OSCAL/issues/1496 are available [here](Overall notes: https://hackmd.io/YS5ib1yMQ4ab-7Ocyy2vUA)
The ADR draft with comments is captured [here](https://hackmd.io/UrSjUKGiQRuiA2VJLG-Mpg)
- ~Have you written new tests …

Adding an ADR for GH labels decluttering (issue #1496 part 1)

---

docs/content/events/_index.md

Fix calendar link that was disabled and no longer shareable from delegate account.

Update calendar share link after weird permissions for #1693.

---

docs/content/contribute/rfc-newsletter/_index.md
docs/content/contribute/rfc-newsletter/newsletter-202303-03.md
docs/layouts/_default/rfc.html

Add RFC Newsletter Archive and March 2023 edition.
Index page:
RFC 1 for 202303 page:

Add RFC newsletter for March 2023 for #1689.

---

docs/content/about/projects/_index.md
docs/content/about/stakeholders/tooldevelopers.md

[RFF] "NIST OSCAL Umbrella of Projects" Page

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/PULL_REQUEST_TEMPLATE.md

Given retro feedback, we will modify the templates.
- Per Chris, Wendell, and others: add a revisions block to the document to not important changes and shift in direction for an issue
- Per Dmitry, be more specific about guidance around what constitutes work that is ready (or reviewable) with a new wiki page
- ~Have …

Update issue templates with retro feedback

---

docs/content/about/_index.md

This PR demonstrates approach 1 for https://github.com/usnistgov/OSCAL/issues/1801 adding the new vision to the top of the about page.

Option 2: vision on about page for #1801.

---

.github/PULL_REQUEST_TEMPLATE.md
docs/content/learn/tutorials/_index.md
docs/content/learn/tutorials/general/_index.md
docs/content/learn/tutorials/general/releases.md

Closes #1809
Also in this PR:
- Fix stray newline in PR template
- ~Have you squashed any non-relevant commits and commit messages? \[[instructions](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History)\]~
- ~~Have you written new tests for your core changes, as applicable?~~
- ~~Have you included examples of how to use your new feature(s)?~~

Document guidance for community to test pre-releases and releases

---

src/utils/util/resolver-pipeline/oscal-profile-test-helper.xsl

This PR removes `default-mode="scrubbing` to avoid an `apply-template` loop when the stylesheet is applied to a document.
By setting `default-mode="scrubbing"` on the `xsl:stylesheet` element, all templates implicitly have the mode `scrubbing`.
When applying this stylesheet to a document, the following template matches:
```
<xsl:template match="/">
<xsl:param name="source" select="." as="document-node()"/>
<xsl:document>
<xsl:apply-templates select="$source" mode="scrubbing"/>
</xsl:document>
</xsl:template>
```
The statement `<xsl:apply-templates select="$source" mode="scrubbing"/>` then causes the same template to match instead of the intended template:
```
<xsl:template mode="scrubbing" match="* | text() | @*">
<xsl:copy>
<xsl:apply-templates mode="#current" select="@*"/> …
```

Restore proper mode handling for `oscal-profile-test-helper.xsl`

---

build/ci-cd/README.md

This PR commit will update the Metaschema submodule to update. We need to update the underlying version of the MIMF to address the following:
Closes usnistgov/OSCAL#1773.
Closes usnistgov/OSCAL#1774.
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you …

Update metaschema for 1.0.6 release

---

src/metaschema/oscal_metadata_metaschema.xml

A community member reported the obsolete references to back-matter/resource/citation biblio element. The documentation that led to the bug report has also since been commented out, this commit will remove both commented out model and documentation.
This PR closes #1841.
- ~Have you written new tests for your core changes, as applicable?~ Removing commented out dead code, so N/A
- ~Have you included examples of how to use your new feature(s)?~ Ditto, see …

Remove dead code for biblio element in citations

---

src/metaschema/oscal_assessment-results_metaschema.xml
src/metaschema/oscal_catalog_metaschema.xml
src/metaschema/oscal_complete_metaschema.xml
src/metaschema/oscal_component_metaschema.xml
src/metaschema/oscal_control-common_metaschema.xml
src/metaschema/oscal_implementation-common_metaschema.xml
src/metaschema/oscal_metadata_metaschema.xml
src/metaschema/oscal_poam_metaschema.xml
src/metaschema/oscal_profile_metaschema.xml
src/metaschema/oscal_ssp_metaschema.xml

Fixes #1883 - Broken links to metaschema submodule content (should be metaschema-xslt + changed paths)
- N/A Have you written new tests for your core changes, as applicable?
- N/A Have you included examples of how to use your new feature(s)?
- N/A Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.

Corrects submodule schema references identified in #1883

---

src/metaschema/oscal_ssp_metaschema.xml

Fixes #1795 by allowing other impact values.
#1872 trialed a broader change, allowing for other impact types falling outside of the CIA triad as well as an `@ns` attribute for optional constraints.
It is clear this issue requires more care. This PR will be followed up with an OSCAL-DEFINE entry https://github.com/usnistgov/OSCAL-DEFINE/issues/34.

Adjusted `information-type/*-impact` constraints

---

.github/workflows/periodic.yml
README.md

Reduce linkchecker spam

---

src/metaschema/oscal_complete_metaschema.xml
src/metaschema/oscal_responsibility-common_metaschema.xml
src/metaschema/oscal_shared-responsibility_metaschema.xml

This PR corrects the errors that remained and prevented publication of the shared responsibility model in OSCAL-Reference.
I was able to reproduce the errors in a fork of the reference, and publish here:
https://chriscompton.github.io/OSCAL-Reference/models/prototype-sr/shared-responsibility/
That should cover the recent feedback @iMichaela.
Once merged into the prototype, manually run the [Pages workflow](https://github.com/usnistgov/OSCAL-Reference/actions/workflows/pages.yaml) in OSCAL-Reference, and it should complete.  If not, just let me know.
The export assembly still appears in the SR model assemblies shared with the SSP.  I did not adjust assemblies to remove this since it would diverge from the SSP model.  I also think this needs to be debated, and a little work will need to be …

Prototype SR model: Correct errors in metaschema for publishing reference.

---

src/metaschema/oscal_assessment-common_metaschema.xml
src/metaschema/oscal_assessment-plan_metaschema.xml
src/metaschema/oscal_assessment-results_metaschema.xml
src/metaschema/oscal_catalog_metaschema.xml
src/metaschema/oscal_complete_metaschema.xml
src/metaschema/oscal_component_metaschema.xml
src/metaschema/oscal_control-common_metaschema.xml
src/metaschema/oscal_implementation-common_metaschema.xml
src/metaschema/oscal_metadata_metaschema.xml
src/metaschema/oscal_poam_metaschema.xml
src/metaschema/oscal_profile_metaschema.xml
src/metaschema/oscal_responsibility-common_metaschema.xml
src/metaschema/oscal_shared-responsibility_metaschema.xml
src/metaschema/oscal_ssp_metaschema.xml

> This PR supersedes  #1999. The new `prototype-shared-responsibility-model-rebased` on usnistgov/OSCAL contains only metaschema updates from the previous prototype rebased against main. This PR contains work by @iMichaela making further updates to the model in preparation for an RC1 after community review.
The prototype shared-responsibility model was updated and the documentation was reviewed. This version of the model is ready for review and integration into the OSCAL v1.2.0 release candidate. The prototype was locally tested with the latest [metaschema-xslt/document-display-deprecation](https://github.com/usnistgov/metaschema-xslt/tree/document-display-deprecation)
By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public …

Updated prototype shared-responsibility model.

---

src/metaschema/oscal_catalog_metaschema.xml
src/metaschema/oscal_mapping-common_metaschema.xml
src/metaschema/oscal_mapping_metaschema.xml

The prototype-mapping-model-rebased model definition files were reviewed, errors fixed and prepared for release candidate RC1 by also advancing the schema-version to 1.3.0.
**IMPORTANT:** This PR should ONLY be merged AFTER the PR #2000 is merged into develop, and rebasing can be done.

Updates to the prototype-mapping-model-rebased in preparation of a release candidate.

---

src/metaschema/oscal_assessment-common_metaschema.xml

Two instances of a orphaned parenthesis which somehow got into develop.
I would recommend improved integration/unit tests to validate to prevent this in the future.

hotfix invalid syntax

---

src/metaschema/oscal_catalog_metaschema.xml

this constraint should be simply a warning.

---

src/metaschema/oscal_ssp_metaschema.xml

Closes #2108.
- ~Have you updated the [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the [OSCAL-Pages](https://github.com/usnistgov/OSCAL-Pages) and [OSCAL_Reference](https://github.com/usnistgov/OSCAL-Reference) …

Make `/system-security-plan/system-implementation/users` optional
