usnistgov/OSCAL

- CONTRIBUTING.md
- README.md
#154: Added discussion of the sprint management approach to CONTRIBUTING.md, specifically addressing status reporting. 
Updated the README.md to point to the OSCAL website and to provide a link to information on contributing.
> Updates to CONTRIBUTING.md to address status reporting and README.md cleanup

- source/layouts/layout.erb
Moved the GitHub link to a a more prominent place in the left navigation.
> Update layout.erb to improve positioning of GitHub link in left navigation

- content/fedramp.gov/FedRAMP_HIGH-baseline_profile.xml
- content/fedramp.gov/FedRAMP_LOW-baseline_profile.xml
- content/fedramp.gov/FedRAMP_MODERATE-baseline_profile.xml
The file naming convention and authoritative location of the NIST 800-53 Rev 4 documents changed after the HREF lines in the FedRAMP profiles were fixed. This brings the FedRAMP profiles fully into alignment, and marks them as version 1.0.
All other Issue #185 items remain fully addressed. A review and acceptance of this pull request should fully resolve Issue #185.
> HREF now correctly points to 800-53

- content/nist.gov/SP800-53/rev4/NIST_SP-800-53_rev4_catalog.xml
A new OSCAL draft catalog corrects a problematic (semantically consequential) bug in the OSCAL SP800-53 catalog, where a "withdrawn" status (property) was being misattributed to controls that are not withdrawn, but only have enhancements associated that are (happen to be) withdrawn.
Otherwise it makes no changes outside of a new timestamp (in the header comment) and document ID (uuid).
This PR should finally align with the upstream master. It replaces withdrawn PR #228, which replaced PR #227. (Slowly, I am figuring out the git bits.)
Removed `<prop class="status">Withdrawn</prop>` from controls not designated as "Withdrawn" in the NVD source data. Without this correction the OSCAL is wrong.
The production pipeline that produces the catalog (not maintained in this branch) has also been …
> Correction patch to SP800-53 catalog

- util/oscal-content-validator.py
Script that easily validates XML and JSON OSCAL files against OSCAL schema. This allows any
OSCAL user to validate (maybe certify at one point?) their content against the OSCAL schema.
Interestingly enough, there are numerous errors in the JSON catalog schema vs. the generated JSON catalog content. I haven't tested any others.
JSON example:
```
$ ./oscal-schema-validator.py -s oscal-catalog-schema.json -f NIST_SP-800-53_rev4_catalog.json
Traceback (most recent call last):
File "./oscal-schema-validator.py", line 58, in <module>
main()
File "./oscal-schema-validator.py", line 54, in main
oscal_validator(args.oscal_schema, args.oscal_file)
File "./oscal-schema-validator.py", line 46, in oscal_validator
validate(data, schema)
File "/usr/lib/python2.7/site-packages/jsonschema/validators.py", …
```
> Add OSCAL content validator

- build/metaschema/xml/oscal-prose-module.xsd
- build/metaschema/xml/produce-xsd.xsl
- schema/demo/base-example.xml
- schema/demo/oscal-test-metaschema.xml
- schema/demo/oscal-test-schema.xsd
- util/convert/md-oscal-converter.xsl
This PR addresses the first half of Issue #284, extending support for prose in the metaschema. With this extension, OSCAL documents will allow simple HTML-style headers in prose and simple tables, along with paragraphs and lists. 
This was pushed forward because it has become a blocker for @brianrufgsa cf Issues #267 and others dependent on it (#270 #271 etc.) It is a backward-compatible change; all documents valid to the old OSCAL schemas will be valid to newer schemas as well. (The schemas do have to be rebuilt before prose is permitted in the documents.)
NB the XML<->markdown pathway has *not* been extended with this support, so conversion scripts are going to break on these elements until we do that.
Also: this change raises the question of whether at lower levels such as catalog and …
> Extending prose to permit HTML headers h1-h6 plus simple tables

- build/metaschema/lib/metaschema-jsondocs-jekyll-uswds.xsl
- build/metaschema/lib/metaschema-xmldocs-jekyll-uswds.xsl
Addressing @anweiss reported cross-linking bug in XML/JSON docs pages.
> Tweaked cross-linking paths between XML and JSON docs

- docs/content/community/index.md
- docs/content/documentation/architecture/catalog.md
- docs/content/documentation/architecture/control.md
- docs/content/documentation/architecture/index.md
- docs/content/documentation/architecture/profile.md
- docs/content/documentation/index.md
- docs/content/documentation/schemas/index.md
- docs/content/learnmore/index.md
- docs/content/learnmore/roadmap.md
The images and a few of the href's were missing the `/OSCAL` path prefix for proper rendering. This PR addresses that.
> Additional relative URL fixes

- build/metaschema/json/json-schema-metamap.xsl
Correction to JSON Schema generation bug Malformed $refs #361.
Bug was introduced with a syntax optimization for users of Metaschema.
{Please provide a brief description of what this PR accomplishes. Be sure to reference any issues addressed. If the PR is a work-in-progress submitted for early review, please include [WIP] at the beginning of the title.}
> Correction to JSON Schema generation pipeline

- build/metaschema/json/json-schema-metamap.xsl
- build/metaschema/json/produce-json-schema.xsl
Addressing issue in escaping quote marks in JSON schema generation.
> Fix json schema escaping

- build/metaschema/json/json-schema-metamap.xsl
- build/metaschema/lib/metaschema.xsd
- build/metaschema/xml/oscal-prose-module.xsd
- content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_HIGH-baseline_profile.xml
- content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_LOW-baseline_profile.xml
- content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_MODERATE-baseline_profile.xml
- content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_catalog.xml
- src/content/fedramp.gov/xml/FedRAMP_HIGH-baseline_profile.xml
- src/content/fedramp.gov/xml/FedRAMP_LOW-baseline_profile.xml
- src/content/fedramp.gov/xml/FedRAMP_MODERATE-baseline_profile.xml
- src/content/mini-testing/oscal_testing_dinosaur_catalog.xml
- src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_HIGH-baseline_profile.xml
- src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_LOW-baseline_profile.xml
- src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_MODERATE-baseline_profile.xml
- src/content/nist.gov/SP800-53/rev4/xml/NIST_SP-800-53_rev4_catalog.xml
- src/metaschema/oscal-catalog-metaschema.xml
- src/metaschema/oscal-profile-metaschema.xml
- xml/schema/oscal-catalog-schema.xsd
- xml/schema/oscal-profile-schema.xsd
Addresses the modeling refinement described in #243 - **title** is no longer permitted at the top (of a catalog or profile) but is required at the top of its **metadata** -- while **metadata** is also required.
Includes fresh copies of the NIST SP800-53 examples (catalog and profiles), now valid XML.
@brianrufgsa please note that FedRAMP examples need their top-level titles removed to be valid to the schemas in this PR.
This PR includes changes made in the branch behind PR #375.
> Metaschema improvement with OSCAL schema adjustments

- build/metaschema/json/md-converter-test.xsl
- build/metaschema/json/md-oscal-converter.xsl
- build/metaschema/json/produce-json-converter.xsl
- build/metaschema/xml/produce-xml-converter.xsl
- src/utils/util/convert/xml-as-json-object.xsl
This PR includes the latest support for bidirectional conversion between XML and Markdown, including tables, images and headers, addressing #283 (completing this feature) and #343 (deploying and testing).
> Bidirectional XML/Markdown conversion support

- build/metaschema/json/json-schema-metamap.xsl
- build/metaschema/lib/metaschema-check.sch
- build/metaschema/lib/metaschema.xsd
- build/metaschema/xml/produce-xsd.xsl
- src/metaschema/oscal_catalog_metaschema.xml
- src/metaschema/oscal_metadata_metaschema.xml
- src/metaschema/oscal_profile_metaschema.xml
- src/metaschema/oscal_ssp_metaschema.xml
Completing Issue #57 by adding version info to XSD and JSON Schema (but see comments for any unresolved questions).
> Completed work reflecting schema version in XSD and JSON schema (#57)

- .circleci/config.yml
Repair for skipping CI deploy builds.
> Added skip step for skipping CI deploy builds

- build/ci-cd/copy-and-convert-content.sh
The prettified JSON produced by the CI/CD workflow is missing quoting in JSON keys. This PR fixes this.
> Ensure that pretty JSON is valid

- build/metaschema/json/produce-json-converter.xsl
- build/metaschema/lib/metaschema-check.sch
- build/metaschema/lib/metaschema-compose.xsl
- build/metaschema/lib/metaschema-jsondocs-jekyll-uswds.xsl
- build/metaschema/lib/metaschema-xmldocs-jekyll-uswds.xsl
- build/metaschema/xml/produce-and-run-either-documentor.xsl
- build/metaschema/xml/produce-xml-converter.xsl
Making content conversion work for us.
> content conversion fixes

- .gitignore
- LICENSE.md
- build/ci-cd/copy-and-convert-content.sh
- build/ci-cd/generate-content-converters.sh
- build/ci-cd/generate-model-documentation.sh
- build/ci-cd/generate-schema.sh
- build/ci-cd/package-release.sh
- build/ci-cd/run-all.sh
- build/ci-cd/validate-content-conversion-round-trips.sh
- build/ci-cd/validate-content.sh
- build/ci-cd/validate-metaschema.sh
- build/metaschema/json/produce-json-converter.xsl
- Fixed a path bug in build scripts when running in MinGW.
- Fixed typos in build script messages.
> Fixes to build scripts

- docs/content/documentation/schemas/datatypes.md
The JSON schema integer type in the datatype docs had the wrong external reference link. This PR addresses this with the correct link.
> Incorrect link to JSON schema integer type in datatypes docs

- build/metaschema/lib/metaschema-common-html.xsl
- build/metaschema/lib/metaschema-jsondocs-hugo-uswds.xsl
- build/metaschema/lib/metaschema-xmldocs-hugo-uswds.xsl
These adjustments to docs production stylesheets restore 'allowed values' listings to field and flag definitions (that have them) - inadvertantly lost in a previous upgrade.
Bug repair - n/a
> Repaired bugs - lapses in 'allowed-values' listings

- build/metaschema/lib/metaschema-jsondocs-hugo-uswds.xsl
- build/metaschema/lib/metaschema-jsonobject-map.xsl
Fixed JSON model map docs, where they mistakenly present a single name not a group name for objects that can be grouped.
A good test is `system-characteristics/annotations` in the SSP model. It showed as singular "annotation", which is wrong here.
> Repaired bug in display of groupable objects in JSON map

- src/metaschema/oscal_catalog_metaschema.xml
- src/metaschema/oscal_metadata_metaschema.xml
- src/metaschema/oscal_profile_metaschema.xml
Addressing #499 and #511.
**n/a - all changes are backward-compatible**
**n/a - self-explanatory**
> Sprint24 model enhancements

- build/metaschema/lib/metaschema-jsondocs-hugo-uswds.xsl
- build/metaschema/lib/metaschema-xmldocs-hugo-uswds.xsl
Repairs a bug preventing links from flag definitions to the field and assembly definitions that call the flag. Reported as #549.
> Restored broken links from flags to their fields/assemblies.

- src/utils/schematron/oscal-profile-catalog-sources.sch
- src/utils/schematron/oscal-profile-sources.sch
Addressing the requirements of #534, this PR adds a small Schematron for simple link checking on profiles.
It is able to detect, when a profile imports from a catalog, whether controls are actually present in the catalog, when called (imported) by a profile.
It doesn't do fancier checking like checking against profile resolutions, or analysis. See the neighbor Schematron `oscal-profile-sources.sch` for this (while it depends on now-outmoded profile resolution).
> Added simple control call link checker Schematron cf Issue #534

- .circleci/config.yml
- docs/content/contribute/devlunch.md
Fixed a build bug causing the maven dependency to not be found. Changed the retrieval URL to use the maven release archive, which keeps historic versions. Also upgraded to maven 3.6.3.
> updated maven version to 3.6.3 to fix missing 3.6.2

- src/metaschema/metaschema-browser.xsl
Previously, OSCAL schema contained `<assembly>` elements along the `<assemblies>` elements. This is no longer true and OSCAL contains only `<assembly>` elements.
> Remove left-over assemblies tooling

- src/metaschema/oscal_metadata_metaschema.xml
#528 describes how we need more consistency in the XML representation of certain (markup-multiline) assemblies. This PR addresses it by adding wrapping to the specification for `description` and `remarks` elements where they did not have it.
No data had to be altered to be valid to the adjusted models.
> Adjusted 'in-xml' settings

- src/content/fedramp.gov/xml/FedRAMP_HIGH-baseline-resolved-profile_catalog.xml
- src/content/fedramp.gov/xml/FedRAMP_LI-SaaS-baseline-resolved-profile_catalog.xml
- src/content/fedramp.gov/xml/FedRAMP_LOW-baseline-resolved-profile_catalog.xml
- src/metaschema/oscal_metadata_metaschema.xml
- src/metaschema/oscal_ssp_metaschema.xml
Enforcing better consistency over definitions of flags intended as IDs or pointers to IDs - XML `NCName` instead of strings. See Issue #551.
> Tightened declaration of flags for identifiers to 'NCName'

- .circleci/config.yml
- docs/Dockerfile
Hugo version 0.69.0 incorrectly handles ancestor pages. This has been fixed in 0.69.2. This PR updates the Hugo version used to 0.69.2.
Fixes #660.
> Update Hugo dependency to correct version

- src/specifications/profile-resolution/readme.md
- src/utils/util/resolver-pipeline/readme.md
Two important readme documents have been updated and improved in this PR:
- how to provide feedback on the Profile Resolution Spec
- how to run the prototype XSLT profile resolver pipeline
Issue #673 points out that we have inoperative instructions in a readme, referring to resources we are no longer making available through this channel (oXygen editing setup). This patch corrects that.
n/a
> #673 - Updating readme for feedback on profile resolution spec

- build/README.md
- src/content/fedramp.gov/xml/FedRAMP_HIGH-baseline_profile.xml
- src/content/ssp-example/json/ssp-example.json
- src/metaschema/oscal_assessment-common_metaschema.xml
- src/metaschema/oscal_implementation-common_metaschema.xml
- src/metaschema/oscal_metadata_metaschema.xml
- src/metaschema/oscal_poam_metaschema.xml
- src/metaschema/oscal_ssp_metaschema.xml
- src/metaschema/readme.md
This addresses the id to uuid issues discussed in issue #691 as well as updates to the POA&M model discussed resulting from work on issue #639.
id to uuid changes include:
- All Models: prop and annotation changed id to uuid. Set uuid to optional (required="no").
- SSP Model: leveraged-authorization changed id to uuid
- SSP Model: information-type changed id to uuid
- SSP Model: changed component-id to component-uuid
> Metaschema Updates - id to uuid fixes, poam tweaks

- .gitmodules
- CONTRIBUTING.md
- build/README.md
Fixing submodule URLs to use HTTP by default closing #753.
> Updating submodules to use HTTP instead of SSH

- src/metaschema/oscal_ssp_metaschema.xml
Updates the SSP metaschema in support of revised leveraged authorization syntax.
> Updated SSP metaschema for leveraged-authorizations

- src/release/content-upgrade/add-uuids.xsl
- src/release/content-upgrade/oscal-m2-m3-elements.xsl
- src/release/content-upgrade/rewrite-links.xsl
Added handling for Milestone 2 constructs (not given in earlier samples) in conversion utility to M3:
* `@name` on `authorized-privilege` becomes `title`
* `information-type/@id` becomes `@uuid`
> Enhancements to M2->M3 data conversion utility

- docs/content/documentation/schema/assessment-layer/assessment-plan/json-schema.md
- docs/content/documentation/schema/assessment-results-layer/assessment-results/json-schema.md
- docs/content/documentation/schema/assessment-results-layer/poam/json-schema.md
- docs/content/documentation/schema/catalog-layer/catalog/json-schema.md
- docs/content/documentation/schema/implementation-layer/component/json-schema.md
- docs/content/documentation/schema/implementation-layer/ssp/json-schema.md
- docs/content/documentation/schema/profile-layer/profile/json-schema.md
Includes configuration change to docs production under Hugo, supporting ToC generation over JSON Schema docs pages.
WIP towards usnistgov/OSCAL#725.
> Modifying configuration of JSON Schema docs pages (toc)

- src/metaschema/oscal_control-common_metaschema.xml
Relaxes requirement on 'prose' field in control common metaschema definitions.
> Adjusted 'prose' cardinality in control-common metaschema

- docs/content/documentation/schema/profile-layer/profile/_index.md
- src/metaschema/oscal_assessment-results_metaschema.xml
As coordinated with @david-waltermire-nist, removed assessment-subject from root of AR. 
Assessment Subject should be defined in root of AP, or local-definitions of AR.
> removed assessment-subject from root of AR

- build/Dockerfile
- build/README.md
- build/ci-cd/copy-and-convert-content.sh
This commit fixes duplicate definition ids in the generated JSON schema which based on metaschema fixes in PR usnistgov/metaschema#116 (issues usnistgov/metaschema#18 and usnistgov/metaschema#113).
Also fixes YAML content conversion.
> Fixes to JSON Schema Generation

- versioning-and-branching.md
This PR proposes a repository versioning and branching strategy to address the discussion #853.
This is a work in progress for early discussion.
> Defining a versioning and branching strategy

- docs/content/contribute/_index.md
- docs/content/contribute/roadmap.md
- src/metaschema/oscal_metadata_metaschema.xml
- Added `canonical`, `alternate`, `predecessor-version`, and `successor-version` to `/o:metadata/o:revision/o:link/@rel`.
- Removed `source` for which `canonical` will be used instead from `/o:metadata/o:revision/o:link/@rel`.
- Fixed a couple references to `master` re-pointing them to `main`.
Resolves #919.
> Added rels for metadata/revision/link

- src/metaschema/oscal_assessment-common_metaschema.xml
- src/metaschema/oscal_assessment-plan_metaschema.xml
- src/metaschema/oscal_assessment-results_metaschema.xml
- src/metaschema/oscal_component_metaschema.xml
- src/metaschema/oscal_implementation-common_metaschema.xml
- src/metaschema/oscal_metadata_metaschema.xml
- src/metaschema/oscal_poam_metaschema.xml
- src/metaschema/oscal_profile_metaschema.xml
- src/metaschema/oscal_ssp_metaschema.xml
A quick search of the metaschemas with the XPath `//*:group-as[@in-json='BY_KEY']` shows the following places where `group-as in-json="BY_KEY"` is used. The following will track conversion to `ARRAY`:
Resolves #914.
> 914 remove by key

- src/metaschema/oscal_assessment-common_metaschema.xml
- src/metaschema/oscal_profile_metaschema.xml
- src/utils/util/resolver-pipeline/oscal-profile-resolve-modify.xsl
In "select-subject-by-id" renamed "uuid-ref" to "subject-uuid" to be more consistent with other cross-references in OSCAL.
Added a required "type" to all subject references.
Renamed attributes in profile "add" and "remove" to eliminate the "-ref" suffix and add the "by-" prefix. Also updated profile resolver code to work with these changes.
Resolves #898.
> Make cross-reference names more consistent

- src/metaschema/oscal_assessment-common_metaschema.xml
- src/metaschema/oscal_complete_metaschema.xml
Adjusting documentation for the risk log, which was copied from the assessment log and never updated to reflect the risk log semantics.
Resolves #907.
> Fix risk log documentation

- src/metaschema/oscal_assessment-results_metaschema.xml
Makes the findings array zero-to-unbounded.
Resolves #918.
> Make assessment findings optional

- src/metaschema/oscal_assessment-common_metaschema.xml
- src/metaschema/oscal_assessment-plan_metaschema.xml
- src/metaschema/oscal_assessment-results_metaschema.xml
- src/metaschema/oscal_catalog_metaschema.xml
- src/metaschema/oscal_complete_metaschema.xml
- src/metaschema/oscal_component_metaschema.xml
- src/metaschema/oscal_control-common_metaschema.xml
- src/metaschema/oscal_implementation-common_metaschema.xml
- src/metaschema/oscal_metadata_metaschema.xml
- src/metaschema/oscal_poam_metaschema.xml
- src/metaschema/oscal_profile_metaschema.xml
- src/metaschema/oscal_ssp_metaschema.xml
Updates to OSCAL Metaschema sources in view of Metaschema processing enhancements addressing #805 and #911.
- New data type: `token` prohibits whitespace and enforces conformity with an XML-NCName workalike (also in JSON)
- Strings no longer permit leading or trailing whitespace
> Metaschema enhancements to string-based datatypes

- src/release/content-upgrade/oscal-rc2-v1-0-0-update.xsl
Adds converter XSLT supporting RC2->v1.0.0 conversion.
> Adding RC2->v1.0.0 converter XSLT

- src/release/content-upgrade/oscal-rc2-v1-0-0-update.xsl
New template in RC2-v1.0.0 conversion XSLT to rewrite values of `select/@how-many` without whitespace (for schema validity).
> Mapping whitespace in values of select/@how-many to hyphens '-'

- .github/workflows/metaschema-artifacts.yml
- .github/workflows/package-release.yml
- build/Dockerfile
> Minor Docker Improvements

- docs/content/tools/_index.md
Just learned about these two projects — want to surface them to other folks that might be interested.
N/A
> link to EasyDynamics OSCAL tools

- src/metaschema/oscal_profile_metaschema.xml
- src/specifications/profile-resolution/profile-resolution-specml.xml
- src/specifications/profile-resolution/specml-html-preview.xsl
- src/specifications/profile-resolution/specml.css
- src/specifications/profile-resolution/specml.rnc
- src/utils/util/readme.md
PR to merge profile resolution specification into origin. Total document rework, includes several small model changes.
> Profile specification

- src/metaschema/oscal_component_metaschema.xml
- src/metaschema/oscal_implementation-common_metaschema.xml
Minor typo fix that closes usnistgov/OSCAL#1067.
> Fix enum typos from inteneral->internal, closes #1067.

- src/utils/util/oscal-content-validator.py
- src/utils/util/requirements.txt
Add support for yaml OSCAL files validation
Added support for yaml OSCAL files validation to `oscal-content-validatory.py`.
> Add support for yaml OSCAL files validation

- src/metaschema/oscal_profile_metaschema.xml
> Make @control-id required for Profile Alter Statements

- docs/content/reference/datatypes.md
Closes #1037.
Updated local build with copy and formatting improvements:
> Clarify Parameter Insert Data Type Docs

- src/utils/util/resolver-pipeline/oscal-profile-resolve-select.xsl
- src/utils/util/resolver-pipeline/testing/1_selected/catalog-no-uuid.xml
- src/utils/util/resolver-pipeline/testing/1_selected/catalog-nonstandard-file-name-ext.xmlcat
- src/utils/util/resolver-pipeline/testing/1_selected/glob-rewrite.xspec
- src/utils/util/resolver-pipeline/testing/1_selected/resource-media-type.xml
- src/utils/util/resolver-pipeline/testing/1_selected/resource-multiple-rlinks.xml
- src/utils/util/resolver-pipeline/testing/1_selected/select-mapping-controls.xspec
- src/utils/util/resolver-pipeline/testing/1_selected/select-rlink.xspec
- src/utils/util/resolver-pipeline/testing/1_selected/select.xspec
The goal of this PR is to add more template-level and function-level XSpec tests for code in `src/utils/util/resolver-pipeline/oscal-profile-resolve-select.xsl`.
While working on that, I also made minor changes in that XSLT file:
- Add support for `with-parent-controls`, to align with latest spec (Is that a "core" feature, so I should complete the "Changes to Core Features" checklist below?)
- Generate fatal error if resource cannot be fetched, to align with latest spec
- Provide focused error message if resource has no suitable rlink
- In `o:selects` function, handle missing matching pattern and address #1075 
- Remove a line of unused code, to address #1081 
I also included preliminary tests for behavior described in the "Mapping Controls" section of the spec. Some of them are marked …
> Profile resolver selection: XSpec additions and minor XSLT enhancements

- docs/content/concepts/_index.md
- docs/content/concepts/processing/_index.md
- src/specifications/profile-resolution/profile-resolution-specml.xml
- src/specifications/profile-resolution/specml.rnc
This pull request includes the following changes to the Profile Resolution Specification:
- Added requirement tagging to the XML source. added "req" to the .rnc schema
- Added a draft status notice to the document and the landing page of the OSCAL website
- Fixed errors in the Modify section (ref-id -> by-id, removed extraneous text)
- Editorial fixes throughout document
> Requirement Tagging - Profile Resolution Specification

- src/metaschema/oscal_assessment-results_metaschema.xml
In all metaschemas, the name `props` is used to signify the list of metadata properties.
This PR fixes an obvious typo in the assessment results metaschema where the name `prop` is used instead of `props`.
This will most likely break backwards compatibility, but since this is an obvious typo/fix I think it is worth considering for versions earlier than `v2.0`.
> Fix name typo from `prop` to `props`

- src/metaschema/oscal_assessment-common_metaschema.xml
- src/metaschema/oscal_assessment-results_metaschema.xml
Similarly to PR #1133, I came across 3 more place where there's an extra closing triangle bracket (`>`) that shows up in the built schemas.
This time I did a global search in the metaschemas for `>>`, so there aren't suppose to be anymore places where this occurs.
> Remove extra `>` which shows in the built schemas

- src/utils/util/resolver-pipeline/testing/1_selected/select-rlink.xspec
Minor follow-up to #1101: For consistency with select.xspec, make select-rlink.xspec use an XSpec variable instead of an entity,
for the path to the profile resolution examples.
I qualified this change by running the test in Oxygen.
- ~~[ ] Have you added an explanation of what your changes do and why you'd like us to include them?~~
- ~~[ ] Have you written new tests for your core changes, as applicable?~~
- ~~[ ] Have you included examples of how to use your new feature(s)?~~
- ~~[ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content directory of your branch.~~
> Use XSpec variable instead of entity

- src/utils/util/resolver-pipeline/random-util.xsl
- src/utils/util/resolver-pipeline/testing/2_metadata/random-util.xspec
random-util.xsl provides r:make-uuid and r:make-uuid-sequence for creating one
or more random UUIDs. The r:make-random-string-sequence function supports
more flexible random patterns. Implementations here use the XPath function,
random-number-generator.
random-util.xspec provides template- and function-level tests for code in random-util.xsl.
This is not a core feature.
- ~~[ ] Have you added an explanation of what your changes do and why you'd like us to include them?~~
- ~~[ ] Have you written new tests for your core changes, as applicable?~~
- ~~[ ] Have you included examples of how to use your new feature(s)?~~
- ~~[ ] Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made …
> Nonrecursive UUID functions plus XSpec tests

- .github/CODEOWNERS
- .github/CONTENTS.md
- .github/ISSUE_TEMPLATE/README.md
- .github/ISSUE_TEMPLATE/question.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/README.md
- CONTRIBUTING.md
- versioning-and-branching.md
Updating readmes with more current and relevant information.
Adding CODEOWNERS to drive reviews.
> Updating core documentation

- src/release/README.txt
- src/release/content-upgrade/README.md
- src/release/content-upgrade/oscal-rc2-v1-0-0-update.xsl
This PR implements a parameter in the RC2 to 1.0.0 content-upgrader script to specify the `xsi:schemaLocation` attribute in the top-level XML node for the given model of that OSCAL document instance when executing the content upgrade. The parameter is empty (`''` string) by default, will intentionally not insert the attribute to be backwards compatible. It will only insert the schema location if explicitly set when a developer overrides it or the XProc pipeline in CI/CD sets it.
This code implements and closes usnistgov/OSCAL#1093. 
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content …
> Parameterize Insertion of xsi:schemaLocation Attribute in Content Upgrader, Disable by Default

- src/metaschema/oscal_profile_metaschema.xml
- src/specifications/profile-resolution/profile-resolution-specml.xml
- src/specifications/profile-resolution/specml-html-hugo-uswds.xsl
Addresses:
#1141 
Enhanced prose around Group handling, especially around expected behavior of the "keep always" prop.
#1142 
Core issue obsoleted by general OSCAL requirements on valid OSCAL documents. Cleaned up prose in the formats section.
#1155 
Fixed incorrect notation in metadata section: props are now properly refereed to as such, rather than using the value of their "name" field.
#1140 
Significant improvements around resolution of internal references. Behavior is now defined for resolving resources with different combinations of "rlink" and "base64". As these /should/ all be equal to one another, there is no standardized order or priority given in the specification at this time.
#1152 
Added Metaschema entries for the new Mapping assembly and it's associated fields/flags. …
> Profile Resolution 1.0.2 Updates

- README_validations.md
Follow on PR per discussion in usnistgov/OSCAL#1153 to split high-level what is validation from how to validate. This is the latter. Per recs from @david-waltermire-nist, drop this in a README in the top-level dir of the project, and keep it separate from the core README.md. Together with usnistgov/OSCAL#1169, this will closes usnistgov/OSCAL#1153.
> Add README around how to validate OSCAL

- src/metaschema/oscal_assessment-common_metaschema.xml
Cleanup of OSCAL Metaschemas to remove duplicate constructs.
> Remove duplicated constructs in OSCAL metaschemas

- src/utils/util/resolver-pipeline/random-util.xsl
Implementing an idea from @wendellpiez: Instead of iterating over a
numeric sequence that represents the position of each character in a
long string, iterate over the sequence of characters.
This change is in the implementation only, not in the function output.
I used ad hoc modifications of the `label="seq-length=10000"` scenario
in the XSpec test to check that the original and modified functions
produce the same UUID sequence.
This PR simplifies some code inside a function.
This PR is not urgent, so no worries if the team can't review it for a while.
Acceleration wasn't an explicit requirement, but I used `measure-time="true"` in an ad hoc XSpec file running in Oxygen to compare the speed of the original and modified functions. The modified function here is slightly faster, e.g., 6% or …
> Random function: Iterate over sequence of characters, not positions

- content/fedramp.gov/README.md
- content/nist.gov/SP800-53/README.md
- content/nist.gov/SP800-53/rev4/README.md
- content/nist.gov/SP800-53/rev5/README.md
- src/metaschema/readme.md
There are currently some links which point to GitHub repos with the `master` branch.
All the repos they're pointing to don't have a `master` branch anymore since it was replaced with `main`.
This PR fixes the links.
FYI - The links still currently work, but show an annoying "Branch master was renamed to main." message every time you follow them.
> Fix GitHub links pointing to `master` branch

- src/metaschema/oscal_ssp_metaschema.xml
Added text defining the correct behavior for SSP processors when the `import-profile` references either an OSCAL profile or catalog. Provided guidance on use of profile references instead of catalog references. Resolves #1211.
> Clarified referencing a profile or catalog in `import-profile`

- src/metaschema/oscal_component_metaschema.xml
- src/metaschema/oscal_ssp_metaschema.xml
Clarified use of set-parameter and how to determine the effective value. Resolves #1206.
> clarified use of set-parameter and how to determine the effective value

- .github/workflows/workflow-generate-metaschema-resources.yml
- .github/workflows/workflow-generate-website-reference.yml
- .github/workflows/workflow-generate-website.yml
Fix logical bug missed in usnistgov/OSCAL#1231 to fix for final release. This really closes usnistgov/OSCAL#1208.
> Fix Broken Booleans Only in `workflow_call` Conditional Cheecks

- docs/content/concepts/identifier-use/_index.md
This PR resolves issue#1256 by removing duplicate text above the callout box on the [Concepts - Identifier Use Page](https://pages.nist.gov/OSCAL/concepts/identifier-use/#identifier-type)
> 1256 concepts identifier use

- src/metaschema/oscal_metadata_metaschema.xml
Clarify YAML media types to minimize ambiguity around the lack of an official IANA Media Registry Type. Closes usnistgov/OSCAL#1255.
> Add clarifying media type documentation for usnisgov/OSCAL#1255.

- README.md
The project's main `README.md` file notes the latest OSCAL version that was released (currently `1.0.1`). This PR removes those references so the `README.md` file doesn't have to be updated with every new OSCAL release.
Additionally, the PR fixes some broken links in the `README.md`.
> Remove references to specific OSCAL releases in`README.md`

- docs/content/reference/datatypes.md
- Updated Metaschema toolchain to correct schema regex bugs. Resolves #1260.
- Updated data type documentation to be consistent with schemas.
> Updated data type documentation and schema constraints to address regex issues

- .github/workflows/link-check.yml
- .github/workflows/workflow-generate-website.yml
- .github/workflows/workflow-validate-repo-markdown.yml
- .github/workflows/workflow-validate-website-content.yml
- CONTRIBUTING.md
- build/config/.markdown-link-check/config.json
Closes usnistgov/OSCAL#1230.
This has been touched up. Before `git commit --amend`ing the final PR, I ran a bad build with known bad links removed  from the ignore, evidenced with [this GitHub Actions "Link Check" workflow run](https://github.com/aj-stein-nist/OSCAL/actions/runs/2335764425).
To sample the Markdown and website content issue format, see the sample bug reports below.
- aj-stein-nist/OSCAL#35
- aj-stein-nist/OSCAL#36
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) …
> Add GHA Workflow for Cron Schedule of Site and Markdown Docs Link Checking

- build/ci-cd/generate-model-documentation.sh
- docs/archetypes/reference-index.md
- docs/layouts/_default/reference-release.html
Dynamically compute remote owner and repo name stub. For the reference model documentation develop branch, we want the owner, repo name, and branch to be dynamically computed and not statically generated and presumed to be from the official main repo, usnistgov/OSCAL. Closes usnistgov/OSCAL#1286
Development snapshot based off of running this branch locally on my workstation with hugo:
Main latest release:
Tagged release:
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the …
> Generate Owner, Repo Stub and Branch URLs Dynamically for Reference Model Docs for Development Snapshot

- .github/workflows/issue-triage.yml
This implements part of usnistgov/OSCAL#1302. See the following example workflow and runs associated with this test configuration.
Example issue with annotated automation: https://github.com/ImportantFederalAgencyTest/remove-project-card-test/issues/12
Successful workflow run creating the issue: https://github.com/ImportantFederalAgencyTest/remove-project-card-test/actions/runs/2463769565
Successful workflow run closing the issue: https://github.com/ImportantFederalAgencyTest/remove-project-card-test/actions/runs/2463777371
**IMPORTANT**:
By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 …
> Remove closed issues from triage board

- build/README.md
Some missed bits from usnistgov/OSCAL#1307. This PR will close usnistgov/OSCAL#1283 once and for all.
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes …
> [skip ci] Update docs for dev env setup per usnistgov/OSCAL#1283.

- .github/workflows/workflow-generate-website.yml
- src/specifications/profile-resolution/profile-resolution-specml.xml
Addresses #1246. Also repairs a few errors in surrounding copy.
> Profile Resolution spec: updated names of 'remove' directives

- src/specifications/profile-resolution/profile-resolution-specml.xml
This pull request updates the profile resolution specification to explain the alter/add/title pattern. This change arises from #1306. Let me know if you think the information should be in a different location or have different phrasing.
> Profile resolution spec: Add req-modify-alter-add-one-title

- src/utils/util/resolver-pipeline/oscal-profile-resolve-finish.xsl
- src/utils/util/resolver-pipeline/testing/5_finished/finish.xspec
This pull request adds template- and function-level XSpec tests for the finish phase of the XSLT profile resolver. It also updates the underlying XSLT, mostly to align with the latest specification.
XSLT
- Remove template that provides link to source, because metadata phase accomplished that
- Add "[last()]" predicate when passing through elements that cannot appear twice
- Align with schema by passing through revisions, document-id, location, and  group/link but not control/annotation
- Align with schema for param insertions, `<insert type="param" id-ref="...">`
- Align with schema and spec for keeping items, `<prop name="keep" value="always">`
XSpec
- Add tests at the level of individual templates
](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-fo …
> Profile resolver: Test finish phase, plus minor XSLT enhancements and fixes

- src/utils/util/resolver-pipeline/oscal-profile-resolve-merge.xsl
- src/utils/util/resolver-pipeline/testing/3_merged/merge.xspec
If a back-matter resource has a keep instruction, the spec
requirement "req-backmatter-keep" says not to replace the
resource unless a later one also has a keep instruction.
This pull request fixes a bug I noticed while working on #1377. If the merge phase replaces a resource having a child element `<prop name="keep" value="always"/>` with a resource that does not, then the finish phase cannot follow the specification's requirement "req-backmatter-keep".
> Profile resolver: Follow keep instruction for back-matter resources

- src/metaschema/oscal_profile_metaschema.xml
Addresses change requested in #1018
> Add remarks field to Profile for modify.alter add/remove

- src/metaschema/oscal_profile_metaschema.xml
- src/specifications/profile-resolution/profile-resolution-examples/catalogs/abc-simple_catalog.xml
- src/specifications/profile-resolution/profile-resolution-examples/modify-adds_profile.xml
- src/specifications/profile-resolution/profile-resolution-examples/output-expected/base-test_profile_RESOLVED.xml
- src/specifications/profile-resolution/profile-resolution-examples/output-expected/base2-test_profile_RESOLVED.xml
- src/specifications/profile-resolution/profile-resolution-examples/output-expected/exclude-call-test_profile_RESOLVED.xml
- src/specifications/profile-resolution/profile-resolution-examples/output-expected/import-twice_profile_RESOLVED.xml
- src/specifications/profile-resolution/profile-resolution-examples/output-expected/include-call-with-children-test_profile_RESOLVED.xml
- src/specifications/profile-resolution/profile-resolution-examples/output-expected/merge-implicit-keep_profile_RESOLVED.xml
- src/specifications/profile-resolution/profile-resolution-examples/output-expected/modify-adds_profile_RESOLVED.xml
- src/specifications/profile-resolution/profile-resolution-specml.xml
Work towards addressing usnistgov/liboscal-java#46.
- Adjusted the profile metaschema to refactor the alter assemblies in a backwards-compatible way.
- Enumerated the set of target item types for remove.
- Fixed references to use current `by-` syntax.
- Adjusted unit tests to support better add/remove testing.
> Profile alter model adjustments

- src/metaschema/oscal_mapping-common_metaschema.xml
Fixed a documentation error caused by copy-and-paste in the mapping model.
- ~~[ ] Have you written new tests for your core changes, as applicable?~~
- ~~[ ] Have you included examples of how to use your new feature(s)?~~
> Corrected mapping `id-ref` documentation

- src/metaschema/oscal_poam_metaschema.xml
Added assembly to support assessment assets.  
(Model already imports from `oscal_assessment-common_metaschema.xml`)
Expected model change:
```
plan-of-action-and-milestones:
local-definitions [0 or 1]: {
components [0 or 1]: [ … ],
inventory-items [0 or 1]: [ … ],
+   assessment-assets [0 or 1]: [ … ],
remarks [0 or 1]: markup-multiline,
},
```
> Add assessment-assets assembly to POAM model. #1291

- src/metaschema/oscal_catalog_metaschema.xml
Added constraint to support retention of the original identifier contained in a catalog as a prop in the target catalog created during profile resolution (identifier reassignment).
> Retain reassigned identifier in catalog props assembly. #1397

- src/metaschema/oscal_ssp_metaschema.xml
This PR fixes issue #1129 .
See issue for the reasoning (and discussion) behind this PR.
> Create `<define-assembly name="impact">` (fix #1129)

- src/metaschema/oscal_metadata_metaschema.xml
A follow-up to usnistgov/OSCAL#1033, a recommended implementation for an `actions` assembly to allow developers using OSCAL to encode approval data for given staff certain `role`s for a `responsible-party` at a certain date and time.
This PR supercedes the obsolete PR usnistgov/OSCAL#1038.
> Add actions assembly to encode an action (i.e. approval) and its role, party, and approval date.

- src/metaschema/examples/rules-component.xml
- src/metaschema/oscal_component_metaschema.xml
- src/metaschema/oscal_rules-common_metaschema.xml
NOTE: This is a migrated PR from usnistgov/OSCAL#1124. OSCAL devs should all be using forks now.
These are examples of metaschema model changes that will be required for usnistgov/OSCAL#1058, and to support example document instances as seen in usnistgov/oscal-content#94.
NOTE: These are labelled WIP (Work In Progress) and are subject to change. Please report feedback on the issue, but also check for updates to the shape of the code as it changes.
> [WIP] Metaschema Enhancements Needed for Rule Construct in Component Definition

- README_validations.md
- build/ci-cd/README.md
- build/ci-cd/python/README.md
- docs/content/contribute/dev-lunch/meeting-2020-05-07.md
- docs/content/contribute/dev-lunch/meeting-2020-05-21.md
- src/metaschema/oscal_implementation-common_metaschema.xml
- src/metaschema/oscal_ssp_metaschema.xml
- xml/README.md
> Add imported-from link rel to relevant SSP assemblies

- src/metaschema/examples/rules-component.xml
- src/metaschema/examples/rules-ssp.xml
- src/metaschema/oscal_ssp_metaschema.xml
This PR will resolve usnistgov/OSCAL#1364.
> More touch-ups to rules model and examples

- .github/workflows/workflow-generate-metaschema-resources.yml
- .github/workflows/workflow-generate-website-reference.yml
- .github/workflows/workflow-generate-website.yml
For Metaschema generation, reference model docs, and website generation, we removed prior consistent use of a GitHub Actions Bot user, as opposed to the default. This made artifact auto-commits harder to notice in the git log and GitHub UI.
This may partially satisfy usnistgov/OSCAL#1448. …
> Add back specifying author for GHA commits

- src/utils/util/resolver-pipeline/oscal-profile-resolve-metadata.xsl
- src/utils/util/resolver-pipeline/testing/2_metadata/metadata.xspec
- src/utils/util/resolver-pipeline/testing/2_metadata/version-util.xspec
- src/utils/util/resolver-pipeline/version-util.xsl
This pull request addresses the "Implemented in XSLT profile resolver" part of #1313 and also adds utility functions for working with Semantic Version 2.0.0 strings.
The opr:oscal-version XSLT function meets the "req-meta-oscal-version" requirement
(MUST) from #1386.
The v:compare utility function helps opr:oscal-version meet the
"req-meta-oscalversion-error" requirement.
> Implement opr:oscal-version function

- src/utils/util/resolver-pipeline/oscal-profile-resolve-modify.xsl
- src/utils/util/resolver-pipeline/testing/4_modified/modify.xspec
This pull request adds template- and function-level XSpec tests for the XSLT profile resolver. It also updates the underlying XSLT, mostly to align with the latest specification.
XSLT
- Warn if set-parameter matches nothing
- Handle more types of children of param
- Make match="control" template handle both implicit and explicit binding
- New oscal:patches-to-id-targeting-ancestor function for processing
needed in multiple places
- For explicit binding that adds a title, add it after original title
to facilitate keeping the right one in finish phase
- For removal by class, expect exact match with no tokenization or
case insensitivity
- In finish phase, keep only last title of a control
XSpec
- Add tests at the level of individual templates and functions …
> Profile resolver: Test modify phase, plus minor XSLT enhancements

- docs/content/reference/datatypes.md
Updated data type documentation adding a note about why NCName was deprecated.
Fixes #1105.
> Clarify difference between NCName and token data types

- src/metaschema/oscal_ssp_metaschema.xml
Based on the request in #784, extended the xpath to include control-origination props for:
```
implemented-requirement/prop
implemented-requirement/by-component/prop
implemented-requirement/statement/prop
implemented-requirement/statement/by-component/prop
```
The updated xpath selected the following paths from my test case:
```
" /system-security-plan[1]/control-implementation[1]/implemented-requirement[1]/prop[1]/@name",
" /system-security-plan[1]/control-implementation[1]/implemented-requirement[1]/prop[2]/@name",
" /system-security-plan[1]/control-implementation[1]/implemented-requirement[1]/prop[3]/@name",
" /system-security-plan[1]/control-implementation[1]/implemented-requirement[1]/statement[1]/prop[1]/@name",
" /system-security-plan[1]/control-implementation[1]/implemented-require …
```
> Support additional control-origination props #784

- src/metaschema/oscal_assessment-common_metaschema.xml
- src/metaschema/oscal_assessment-results_metaschema.xml
- src/metaschema/oscal_poam_metaschema.xml
To match the pattern of POAM for handling observations and risks, a `related-findings` assembly was added.
> POAM related finding support, fixes #1120

- README.md
- content/fedramp.gov/README.md
Update FedRAMP GH links to updated paths, fixes usnistgov/OSCAL#1523.
See last nightly link checker run for more details via URL below.
https://github.com/usnistgov/OSCAL/actions/runs/3359592310/jobs/5567773731
- ~Have you …
> Update outdated links in Markdown files tripping link checker

- build/ci-cd/validate-content.sh
- src/utils/schematron/oscal-profile.sch
Integrate the profile Schematron checker into CI/CD scripts for use in usnistgov/oscal-content. Will contribute to, but not fix or completely close, usnistgov/oscal-content#128. …
> OSCAL Profile Checking with Schematron in CI/CD

- docs/content/reference/datatypes.md
Reduced the amount of 'OSCAL' references in data type documentation. This will make it easier to sync the data types between OSCAL and Metaschema documentation.
> Reduced the amount of 'OSCAL' references in data type documentation

- src/metaschema/oscal_metadata_metaschema.xml
Defined a constraint to validate the allowed characters for a fragment. Resolves #756.
Added a new flag to link name `resource-fragment` to indicate the URI [fragment](https://www.rfc-editor.org/rfc/rfc3986#section-3.5) to append to any `rlink` associated with the referenced `resource`.
Resolves #756.
> Adding resource-fragment flag to link

- docs/content/concepts/layer/implementation/component-definition/_index.md
Fix cdef tutorial URL for usnistgov/OSCAL#1557.
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in …
> Fix CDEF Tutorial Link in CDEF Layers Overview Page

- src/metaschema/oscal_metadata_metaschema.xml
Repairing syntax errors in Metapath expressions.
> Fixed syntax errors in metapaths

- build/pom.xml
This is pulling over workaround as reported in usnistgov/oscal-content#139 with the WIP workaround submodule.
https://github.com/usnistgov/oscal-content/pull/139/commits/26f0fe160932016638575cfafdc55d796d4c6f5b
- ~Have you updated all website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes you made? Changes to the website can be made in the website/content directory of your branch.~
> Workaround maven.restlet.org service cert expiry.

- build/ci-cd/validate-content.sh
Fix rel path from XSLT transform source issue, closes usnistgov/OSCAL#1603.
> Fix OSCAL Profile Schematron Relative Paths for GHA

- CONTRIBUTING.md
- docs/content/contribute/_index.md
Fix valid, but failing GH project link for #1620. This link failure blocked the proper deployment of website content to usnistgov/OSCAL#1614 after merge regarding new public calendars.
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? …
> Fix valid, but failing GH project link for #1620.

- docs/content/tools/_index.md
NIST OSCAL Tools page points now to the community-maintained resources  [Awesome OSCAL](https://github.com/oscal-club/awesome-oscal).
> Addressed issue #1599 : Updated tool page on OSCAL pages

- docs/content/contribute/_index.md
- docs/content/events/_index.md
**DO NOT MERGE** before usnistgov/OSCAL#1638 is approved and merged in.
Current design looks as of last commit like the screenshot below. Will update as the commit evolves.
If approved and merged, this closes #1408.
](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)"?~
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected …
> Add shared calendar invite to site

- src/metaschema/oscal_implementation-common_metaschema.xml
See #1521 for detail.
Add WARNING constraints for the port-range assembly when there are issues with the port start and end. 
(Assuming this prevents breaking change, but if that's not true, let me know what level it should be.)
This covers:
- Port range start and end not specified.
- Port range start specified without an end.
- Port range end specified without a start.
- Port range end is less than the start.
> Require (Warn) port start and end when protocol is specified.

- src/utils/util/resolver-pipeline/oscal-profile-RESOLVE.xsl
- src/utils/util/resolver-pipeline/oscal-profile-resolve-metadata.xsl
- src/utils/util/resolver-pipeline/oscal-profile-resolve-modify.xsl
- src/utils/util/resolver-pipeline/oscal-profile-resolve-select.xsl
- src/utils/util/resolver-pipeline/random-util.xsl
- src/utils/util/resolver-pipeline/select-or-custom-merge.xsl
- src/utils/util/resolver-pipeline/testing/1_selected/select.xspec
- src/utils/util/resolver-pipeline/testing/2_metadata/random-util.xspec
This PR addresses issue #1629 by replacing usage of `document-uri` with `base-uri`. The `document-uri` function is known to return different results in Saxon 10 vs. 11. Using `base-uri` removes a difference in the XSLT profile resolver's behavior between Saxon 10 and 11.
Unlike #1639, this PR builds on the head of the develop branch and does not include code from #1596 or #1549.
(Note: #1639 has the same update, but mixed with other code. This pull request isolates the code for Saxon 11 compatibility.) …
> Profile resolver: Compatibility with Saxon 10 and 11

- docs/assets/scss/schema-docs.scss
Fixes #1365
Choices are now displayed in outlines as follows:
JSON view:
XML view:
Nested choices alternate between white (the background color) and light gray up to a depth of 3 (I assume if things get deeper then 3 levels of choices, we have other problems)
This change has been tested on both Firefox and Chrome.
@aj-stein-nist suggested changing the color to fit our palette, as well as re-adding a bit of indentation:
> Fix CSS for choice elements in outline docs

- decisions/0003-github-labels-decluttering.md
- decisions/0004-issue-triage.md
Add an ADR to document the current issue triage process and plot a way forward. Closes #1633.
- ~Do all automated CI/CD checks pass?~
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the …
> Documenting Current and Improved OSCAL Issue Triage Process

- docs/content/events/_index.md
Correct typo and fix links for #1711.
> Correct issues on events page

- src/metaschema/oscal_profile_metaschema.xml
- src/specifications/profile-resolution/profile-resolution-specml.xml
Add `with-parent-controls` to the OSCAL Profile metaschema to match current specification requirements for #1662.
> Add the with-parent-controls for #1662.

- src/metaschema/oscal_ssp_metaschema.xml
Per usnistgov/OSCAL#1552 analysis, the original analysis and provenance for this is unclear and the name indicates its intended use overlaps with more accurate mechanisms available for the implemented requirement. I cannot find a way to write clearer documentation better that cannot explain it, so I opt to remove it.
Closes usnistgov/OSCAL#1552.
- ~Have you included examples of how …
> Remove optional leveraged-authorization prop on implemented-requirement

- .github/workflows/workflow-generate-website.yml
Update PAT configuration for builds, monitor rate limiting, and disable per commit link checking for PRs. Closes #1698 and #1726. 
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the docs/content …
> Update Actions to Properly Use PAT for Website Build and Deployment (#1726)

- build/Dockerfile
Fix classpath configuration of Saxon with `SAXON_CP` environment variable so locally developing with XSLT and XSpec tests works in the container, closes #1743.
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website …
> Specify classpath for Saxon under XSpec for #1743.

- build/ci-cd/validate-metaschema.sh
- build/pom.xml
Update metaschema for current datatype regexes, closes #1703.
- ~Do all automated CI/CD checks pass?~
> Datatype regex fixes for #1703

- src/utils/util/resolver-pipeline/oscal-profile-resolve.sh
The profile resolution wrapper can now handle spaces in arguments.
> Handle spaces in profile resolution wrapper

- .github/workflows/xspec-tests.yml
- .gitignore
- build/build-oscal-env-dockerfile.sh
- build/pull-oscal-env-dockerfile.sh
- src/utils/util/resolver-pipeline/testing/test.sh
This PR provides a simple helper script to run XSpec tests & an acompanying GitHub action.
> XSpec test suites script & CI

- docs/assets/scss/schema-docs.scss
- docs/layouts/partials/foot.html
Partial fix for usnistgov/issue#1681
These two files hoos up anchors-js stuff for the older style deep-links at the recommended time in the event-lifecycle
Also makes sure that CSS hooks up behaviors to old site and ignores the newer versions.
- ~Have you written new tests for your core changes, as …
> Update Style for Generating Reference Model Anchors at Build Time

- build/README.md
The steps cannot be copied and pasted as-is because the `chown` command
is missing a `$` for the `USER` variable for the group argument. This
also adds quotation marks around the variables.
> Add missing `$` in Linux build setup steps

- .github/workflows/xspec-tests.yml
As it stands, since we are evaluating using the Docker Hub registry that is not public to facilitate NIST Team development to be more efficient for local and remote testing. As this container may not exist at first commit of branch, disable on fork-based PRs for now.
Material to #1814 but does not close it.
- ~Have you …
> Don't build container for XSpec testing for fork-based PRs

- src/metaschema/oscal_control-common_metaschema.xml
- src/metaschema/oscal_implementation-common_metaschema.xml
The next [Metaschema release](https://github.com/usnistgov/metaschema/tree/develop) will corrects a bug that allowed inline field and flag definitions to use `use-name`. This was not intended, but has been used in OSCAL. To ensure alignment with this Metaschema change, this PR refactors out the need to use `use-name` in the two places where it is used.
This PR targets the `release-1.0` branch, but should also be applied to develop.
(For reviewers: …
> Adjustments to align with Metaschema schema bug fixes

- src/metaschema/oscal_component_metaschema.xml
- src/metaschema/oscal_implementation-common_metaschema.xml
`asset-type` will now `allow-other` values making the property less strictive 
- …
> 1797 allow local definition of asset type prop values

- src/metaschema/oscal_ssp_metaschema.xml
Made security-sensitivity-level and security-impact-level optional attributes. Closes #1798. 
> Added changes for #1798

- build/pom.xml
- src/utils/resolver-pipeline/oscal-profile-resolve.sh
This PR corrects some relative paths in `oscal-profile-resolve.sh` and restores a Maven POM dependency file for usnistgov/oscal-content#204. It will be needed to further that work.
- ~Have you written new tests for your core changes, as applicable?~ These changes are not part of core.
- ~Have you included examples of how to use your new feature(s)?~ N/A
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by …
> Script and dependency fixes for v1.1.0 content updates

- build/xslt-runner.sh
This script is being added to facilitate running XSLT stylesheets, such as the XML/JSON JSON/XML conversion utilities that will be used in our oscal-content and related pipelines.
This script will be committed to coincide with testing and review of the Makefile in usnistgov/oscal-content#204. …
> Add XSLT runner utility

- src/utils/resolver-pipeline/Makefile
Very small PR. This change silences the maven download for the resolver pipeline test suite. Currently maven adds several thousand lines of useless output to CI/CD.
Note that the test suite is still in an unstable state (and its output is explicitly ignored in CI/CD). The `copy-dependencies` step is still a bit of a hack until we can run XSpec tests without having dependencies in a specific place.
> Add `--quiet` to the resolver test mvn download

- build/Makefile
Fixes bug where validation checks do not download NPM dependencies before running `npx`, causing error message.
> Add `node_modules` as dependency to AJV validation

- build/.gitignore
- src/metaschema/oscal_assessment-common_metaschema.xml
- src/metaschema/oscal_assessment-plan_metaschema.xml
- src/metaschema/oscal_assessment-results_metaschema.xml
- src/metaschema/oscal_catalog_metaschema.xml
- src/metaschema/oscal_complete_metaschema.xml
- src/metaschema/oscal_component_metaschema.xml
- src/metaschema/oscal_implementation-common_metaschema.xml
- src/metaschema/oscal_metadata_metaschema.xml
- src/metaschema/oscal_poam_metaschema.xml
- src/metaschema/oscal_profile_metaschema.xml
- src/metaschema/oscal_ssp_metaschema.xml
> Version bumping and other minor release prep activities

- src/specifications/profile-resolution/readme.md
Updates links in the `src/specifications/profile-resolution/readme.md`. Closes #1926.
- ~Do all automated CI/CD checks pass?~ (Will follow up see https://github.com/usnistgov/OSCAL/issues/1926#issuecomment-1722607532 for unrelated issue but still from link checking.) …
> 1929 update markdown link

- build/markdown-link-check.json
Ignore linux.die.net man page mirror which seems to fail link update PR and other commits targeting `develop` and `main`. Closes #1926 for good (with a related but different failure).
- ~Have you updated all [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the …
> Ignore link check failures for xmllint man page

- src/specifications/profile-resolution/profile-resolution-examples/output-expected/merge-keep_profile_RESOLVED.xml
This pull request fixes one of the expected output files in the set of sample profiles. Based on the content of the catalog whose controls are being imported, the prop names should be "label" instead of "place" and the a1 statement paragraph should include `<insert>`.
I also noticed a debugging message I had left in the XSLT profile resolver code inadvertently with #1321, so I'm removing that message.
- ~Have you included examples of how to use your …
> Fix expected content of resolving merge-keep_profile.xml

- src/specifications/profile-resolution/profile-resolution-examples/catalogs/abc-multiple-children_catalog.xml
- src/specifications/profile-resolution/profile-resolution-examples/output-expected/without-parent_profile_RESOLVED.xml
- src/specifications/profile-resolution/profile-resolution-examples/without-parent_profile.xml
- src/utils/resolver-pipeline/select-or-custom-merge.xsl
- src/utils/resolver-pipeline/testing/1_selected/select.xspec
This PR fixes a profile resolver bug I noticed, where a certain XSLT template needs to declare its return data type `as="element(o:control)*"` instead of `as="element(o:control)?"`. An unselected parent can have multiple children that are selected, so the data type must accommodate multiple elements.
> Profile resolver bug fix for selected children of unselected parent

- src/specifications/profile-resolution/profile-resolution-examples/import-profile2_profile.xml
- src/specifications/profile-resolution/profile-resolution-examples/import-profile_profile.xml
- src/specifications/profile-resolution/profile-resolution-examples/output-expected/import-profile2_profile_RESOLVED.xml
- src/specifications/profile-resolution/profile-resolution-examples/output-expected/import-profile_profile_RESOLVED.xml
- src/utils/resolver-pipeline/oscal-profile-RESOLVE.xsl
- src/utils/resolver-pipeline/oscal-profile-resolve-select.xsl
- src/utils/resolver-pipeline/testing/1_selected/select.xspec
- src/utils/resolver-pipeline/testing/2_metadata/metadata.xspec
- src/utils/resolver-pipeline/testing/5_finished/finish.xspec
This PR implements support in the XSLT profile resolver for an XML profile importing an XML profile. This is a feature that the spec describes and that was partially implemented by @wendellpiez earlier.
This PR builds on top of #1549, so it might be simpler to merge that PR first. Let me know if I should create this PR in a different way when it depends on unmerged code. What's new in this PR are commits ccef4cfa7d3e05451c53d8d5ead5cc2d760479c0 and 883e1f32a33afc575eeb958081e53dfda4e2db37, containing the following pieces.
XSLT changes:
* Pass $trace global param from top level to selection phase
so it can be passed back to top level in recursion
* When calling pipeline steps, output a trace message before
and after, to make recursive operation clearer
* Handle terminating errors during …
> Profiler resolver support for importing another profile

- .github/workflows/issue-triage.yml
The old board (https://github.com/usnistgov/OSCAL/projects/52) has been deprecated and it is time to switch board automation. Repo admins will get emails on every triage automation failure as old board is closed. There is no attached issue as this work is helpful to ensure there is a limited gap in triage board coverage as we finish the initial migration from the old per-project boards.
- ~Have you written new tests for your core changes, as applicable?~ N/A …
> Update automation to centralized triage board

- src/utils/resolver-pipeline/message-handler.xsl
- src/utils/resolver-pipeline/oscal-profile-RESOLVE.xsl
- src/utils/resolver-pipeline/oscal-profile-resolve-finish.xsl
- src/utils/resolver-pipeline/oscal-profile-resolve-merge.xsl
- src/utils/resolver-pipeline/oscal-profile-resolve-metadata.xsl
- src/utils/resolver-pipeline/oscal-profile-resolve-modify.xsl
- src/utils/resolver-pipeline/oscal-profile-resolve-select.xsl
- src/utils/resolver-pipeline/select-or-custom-merge.xsl
- src/utils/resolver-pipeline/testing/1_selected/message-handler.xspec
- src/utils/resolver-pipeline/testing/1_selected/select-mapping-controls.xspec
- src/utils/resolver-pipeline/testing/1_selected/select-rlink.xspec
- src/utils/resolver-pipeline/testing/1_selected/select.xspec
- src/utils/resolver-pipeline/testing/2_metadata/metadata.xspec
- src/utils/resolver-pipeline/testing/2_metadata/uuid-method-choice.xspec
- src/utils/resolver-pipeline/testing/3_merged/merge-combine.xspec
- src/utils/resolver-pipeline/testing/3_merged/merge.xspec
- src/utils/resolver-pipeline/testing/4_modified/modify.xspec
- src/utils/resolver-pipeline/testing/5_finished/finish.xspec
- src/utils/resolver-pipeline/uuid-method-choice.xsl
Another attempt at rebasing the previously reviewed PR https://github.com/usnistgov/OSCAL/pull/1549. The base is `develop` and all the files I changed are under `src/utils/resolver-pipeline`. There are 2 commits:
* 18d52faf82279b07dab9ddb3da1040b25e68f162 - recreating the work from 1549, off the current state of the develop branch
* 1b1068f1b11d445fcfc0e866604c04850fd0e0e8 - changing 3 directory paths now that the profile resolver code has changed its directory hierarchy
I ran all the profile resolver XSpec tests in Oxygen and there are no failures.
@aj-stein-nist : Is this pull request a reasonable replacement for #1549, or does #1943 have some advantage?
{Please provide a brief description of what this PR accomplishes. Be sure to reference any issues addressed. If the PR is a …
> Profiler error handling

- decisions/0009-tutorials-system-lifecycle.md
Relates to #1893
*Note: This ADR is numbered `0009` even though presently `develop` does not contain `0008`, which is [currently in a state of review](https://github.com/usnistgov/OSCAL/pull/1947)*
> ADR: Design simplified system lifecycle for example system in tutorials

- .github/CODEOWNERS
Codeowners file now defaults to `@usnistgov/itl-oscal-maintainers`.
> Flatten codeowners

- src/utils/resolver-pipeline/select-or-custom-merge.xsl
- src/utils/resolver-pipeline/testing/1_selected/select.xspec
Remove with-parent-controls from implementation XSLT profile resolver used by oscal-content and current OSCAL release builds and associated tests. Closes #1816.
> Remove with-parent-controls from implementation

- build/markdown-link-check.json
Skipping the lychee link check for OSCAL site on csrc due to very slow site response which causes high percent of link check failure
> Skip the link check for the OSCAL site on csrc server.

- src/utils/resolver-pipeline/testing/1_selected/select-mapping-controls.xspec
- src/utils/resolver-pipeline/testing/1_selected/select-rlink.xspec
- src/utils/resolver-pipeline/testing/1_selected/select.xspec
- src/utils/resolver-pipeline/testing/2_metadata/uuid-method-choice.xspec
- src/utils/resolver-pipeline/testing/3_merged/merge-custom.xspec
- src/utils/resolver-pipeline/testing/4_modified/modify.xspec
This PR imitates changes in xslt3-functions PR#7 to make XSpec tests compatible with CI/CD.
- CI/CD puts compiled XSpec file somewhere else, so define ov:service variable more robustly so that uuid-value.txt will be found regardless of where compiled XSpec file is.
- Java UUID class is not found in CI/CD, so conditionalize tests that use it. Running XSpec in Oxygen finds the class and verifies its results (same as before this change).
By submitting a pull request, you are agreeing to provide this contribution under the [CC0 1.0 Universal public …
> Updates to accommodate CI/CD

- src/metaschema/oscal_implementation-common_metaschema.xml
Correcting the `port-range` constraints to properly implement the intent for the defined constraints.
Current port-range constraints are generating warnings that port-range start or end must be defined even when they are.
The following schematron file can be used. If deemed necessary, it can be uploaded to the repo. Example sip file can also be uploaded to oscal-content repo.
```
<?xml version="1.0" encoding="UTF-8"?>
<sch:schema …
```
> Port range constraints re-written to eliminate the error documented in #2023 and oscal-cli/#290

- src/metaschema/oscal_metadata_metaschema.xml
Based on [some testing](https://github.com/usnistgov/OSCAL/issues/2053#issuecomment-2467122855), the required digest lengths should be twice their current size to be correct. This PR adjusts the values to be the correct size.
Resolves #2053 
> Correct digest lengths

- src/metaschema/oscal_assessment-common_metaschema.xml
This PR adds constraints for assessment results facets for [CVSS v4.0](https://www.first.org/cvss/v4-0/).
The names and values used are the initialisms used in the CVSS vector string, to provide for a more concise representation that aligns with how CVSS is commonly used in many tools.
> Add CVSS v4 Facet Support

- src/metaschema/oscal_ssp_metaschema.xml
Fixes #2073.
- ~Have you written new tests for your core changes, as applicable?~ This repo does not contain model-based/instance-based testing; we will update the GSA FedRAMP Automation Team's test suite accordingly for public review and ongoing use.
- ~Have you included examples of how to use your new feature(s)?~ Not in this repository, but will work with GSA FedRAMP Automation Team to update our constraints and examples accordingly.
- ~Have you updated …
> Remove erroneous service/system indices for #2073

- src/metaschema/oscal_implementation-common_metaschema.xml
This documentation fix clarifies ambiguity about how transport layer ports conform with standards that layer on top of the Internet Protocol (IPv4, IPv6 for now, potentially others in the future), not directly as only as "IPv4 port ranges" as it implies.
Closes #2065.
- ~Have you written new tests for your core changes, as applicable?~ This repo does not contain model-based/instance-based testing; we will update the GSA FedRAMP Automation Team's test suite …
> Clarify protocol port-range docs for #2065

- src/metaschema/oscal_component_metaschema.xml
This change fixes #1913 and relates partially to #1922. FedRAMP staff have analyzed the progression of this constraint as it pertains to FedRAMP's tailored use of NIST SP 800-53 controls customized for FedRAMP processes. Previously, it was believed with a representation of a SSP prior to the "this-system" component construct that limiting the protocol assembly usage to _only_ components of service type was feasible. However, this does not allow homogenous this-system-component-based SSPs to have the same requirement. Moreover, this limits the ability of understandably different sub-component of components approaches with complex multi-layered architecture to have non-service components (those of type software, hardware, etc.) document their ports and have it filter up into later …
> Relax component protocol constraint for #1913

- src/metaschema/oscal_implementation-common_metaschema.xml
Per discussion with community members and the nature of port, protocol, and service declarations in a OSCAL SSP model instances for RMF use cases, like FedRAMP and others. It would appear the model, per the Metaschema declarations and documentation, require a port range has a name that is commonly the IANA service name, which should be optional. Otherwise, developers and security officials will need to create an arbitrary name that does not strictly conform to the documentation. More details can be found in the issue thread referenced below by URL.
https://github.com/usnistgov/OSCAL/issues/1772#issuecomment-2466441626
This PR may not completely bring #1772 to resolution, but it may be sufficient to close the issue with one possible approach.
By submitting a pull request, you are agreeing …
> Do not require a `protocol/@name` for #1772

- src/metaschema/oscal_implementation-common_metaschema.xml
This PR resolves issue #2082 by removing the constraint that is preventing use of `protocol` assembly on components of any type other than "service".  
> Remove component protocol constraint

- src/metaschema/oscal_implementation-common_metaschema.xml
- src/metaschema/shared-constraints/allowed-values-property-name-networked-components.ent
> Adjust direction prop constraint and other related constraints for interconnection and other network components

- src/metaschema/oscal_assessment-common_metaschema.xml
- src/metaschema/oscal_assessment-plan_metaschema.xml
- src/metaschema/oscal_assessment-results_metaschema.xml
- src/metaschema/oscal_catalog_metaschema.xml
- src/metaschema/oscal_component_metaschema.xml
- src/metaschema/oscal_control-common_metaschema.xml
- src/metaschema/oscal_implementation-common_metaschema.xml
- src/metaschema/oscal_metadata_metaschema.xml
- src/metaschema/oscal_poam_metaschema.xml
- src/metaschema/oscal_profile_metaschema.xml
- src/metaschema/oscal_ssp_metaschema.xml
This PR closes #2088 once reviewed, approved, and merged.
- ~Have you updated the [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the [OSCAL-Pages](https://github.com/usnistgov/OSCAL-Pages) and …
> Given all in-model constraints IDs

- .github/workflows/status.yml
- src/metaschema/oscal_assessment-common_metaschema.xml
If accepted, closes #2104.
- ~Have you written new tests for your core changes, as applicable?
- ~Have you included examples of how to use your new feature(s)?
- ~Have you updated the [OSCAL website](https://pages.nist.gov/OSCAL) and readme documentation affected by the changes you made? Changes to the OSCAL website can be made in the [OSCAL-Pages](https://github.com/usnistgov/OSCAL-Pages) and [OSCAL_Reference](https://github.com/usnistgov/OSCAL-Reference) …
> Propose renaming observation type from `finding` -> `implementation-issue`
